// Auto-generated declaration for strings
// Generated by: serv add strings

declare module "strings" {
    fn Clone(s: string) -> string
    fn Compare(a, b: string) -> int
    fn Contains(s, substr: string) -> bool
    fn ContainsAny(s, chars: string) -> bool
    fn ContainsFunc(s: string, f: string) -> bool
    fn ContainsRune(s: string, r: string) -> bool
    fn Count(s, substr: string) -> int
    fn Cut(s, sep: string) -> string
    fn CutPrefix(s, prefix: string) -> string
    fn CutSuffix(s, suffix: string) -> string
    fn EqualFold(s, t: string) -> bool
    fn Fields(s: string) -> []string
    fn FieldsFunc(s: string, f: string) -> []string
    fn FieldsFuncSeq(s: string, f: string) -> string
    fn FieldsSeq(s: string) -> string
    fn HasPrefix(s, prefix: string) -> bool
    fn HasSuffix(s, suffix: string) -> bool
    fn Index(s, substr: string) -> int
    fn IndexAny(s, chars: string) -> int
    fn IndexByte(s: string, c: string) -> int
    fn IndexFunc(s: string, f: string) -> int
    fn IndexRune(s: string, r: string) -> int
    fn Join(elems: []string, sep: string) -> string
    fn LastIndex(s, substr: string) -> int
    fn LastIndexAny(s, chars: string) -> int
    fn LastIndexByte(s: string, c: string) -> int
    fn LastIndexFunc(s: string, f: string) -> int
    fn Lines(s: string) -> string
    fn Map(mapping: string, s: string) -> string
    fn Repeat(s: string, count: int) -> string
    fn Replace(s, old, new: string, n: int) -> string
    fn ReplaceAll(s, old, new: string) -> string
    fn Split(s, sep: string) -> []string
    fn SplitAfter(s, sep: string) -> []string
    fn SplitAfterN(s, sep: string, n: int) -> []string
    fn SplitAfterSeq(s, sep: string) -> string
    fn SplitN(s, sep: string, n: int) -> []string
    fn SplitSeq(s, sep: string) -> string
    fn Title(s: string) -> string
    fn ToLower(s: string) -> string
    fn ToLowerSpecial(c: string, s: string) -> string
    fn ToTitle(s: string) -> string
    fn ToTitleSpecial(c: string, s: string) -> string
    fn ToUpper(s: string) -> string
    fn ToUpperSpecial(c: string, s: string) -> string
    fn ToValidUTF8(s, replacement: string) -> string
    fn Trim(s, cutset: string) -> string
    fn TrimFunc(s: string, f: string) -> string
    fn TrimLeft(s, cutset: string) -> string
    fn TrimLeftFunc(s: string, f: string) -> string
    fn TrimPrefix(s, prefix: string) -> string
    fn TrimRight(s, cutset: string) -> string
    fn TrimRightFunc(s: string, f: string) -> string
    fn TrimSpace(s: string) -> string
    fn TrimSuffix(s, suffix: string) -> string
    fn NewReader(s: string) -> string
    fn NewReplacer(oldnew: string) -> string
}
