package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"serv/compiler"
)

func deployServ(srvFile, target string) {
	absPath, err := filepath.Abs(srvFile)
	if err != nil {
		fmt.Printf("Error: %v\n", err)
		os.Exit(1)
	}

	// Parse the source to extract metadata (port, app name)
	program, err := parseWithDependencies(absPath, make(map[string]int))
	if err != nil {
		fmt.Printf("Error parsing %s: %v\n", srvFile, err)
		os.Exit(1)
	}

	appName := strings.TrimSuffix(filepath.Base(srvFile), ".srv")
	port := "8080"

	// Extract port from server statement
	for _, stmt := range program.Statements {
		if srv, ok := stmt.(*compiler.ServerStmt); ok {
			if lit, ok := srv.Value.(*compiler.StringLiteral); ok {
				port = lit.Value
			}
		}
	}

	targetDir := filepath.Dir(absPath)

	switch target {
	case "fly":
		generateFlyConfig(targetDir, appName, port, srvFile)
	case "railway":
		generateRailwayConfig(targetDir, appName, srvFile)
	case "render":
		generateRenderConfig(targetDir, appName, port, srvFile)
	case "docker":
		dockerizeServ(srvFile)
	default:
		fmt.Printf("Unknown deploy target: %s\n", target)
		fmt.Println("Supported targets: fly, railway, render, docker")
		os.Exit(1)
	}
}

func generateFlyConfig(targetDir, appName, port, srvFile string) {
	flyToml := fmt.Sprintf(`# Generated by: serv deploy --target fly
app = "%s"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "%s"

[http_service]
  internal_port = %s
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
`, appName, port, port)

	dockerfile := fmt.Sprintf(`FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY . .
RUN go build -o serv.exe .
RUN ./serv.exe build %s -o service

FROM alpine:3.20
RUN apk --no-cache add ca-certificates
WORKDIR /app
COPY --from=builder /app/service .
EXPOSE %s
CMD ["./service"]
`, srvFile, port)

	flyPath := filepath.Join(targetDir, "fly.toml")
	dockerPath := filepath.Join(targetDir, "Dockerfile")

	if err := os.WriteFile(flyPath, []byte(flyToml), 0644); err != nil {
		fmt.Printf("Failed to write fly.toml: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(dockerPath, []byte(dockerfile), 0644); err != nil {
		fmt.Printf("Failed to write Dockerfile: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("✓ Generated fly.toml and Dockerfile for '%s'\n", appName)
	fmt.Println("\nNext steps:")
	fmt.Println("  1. Install flyctl: https://fly.io/docs/flyctl/install/")
	fmt.Println("  2. fly auth login")
	fmt.Printf("  3. fly apps create %s\n", appName)
	fmt.Println("  4. fly deploy")
}

func generateRailwayConfig(targetDir, appName, srvFile string) {
	railwayJSON := fmt.Sprintf(`{
  "$schema": "https://railway.app/railway.schema.json",
  "build": {
    "builder": "DOCKERFILE",
    "dockerfilePath": "Dockerfile"
  },
  "deploy": {
    "restartPolicyType": "ON_FAILURE",
    "restartPolicyMaxRetries": 10
  }
}
`)

	dockerfile := fmt.Sprintf(`FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY . .
RUN go build -o serv.exe .
RUN ./serv.exe build %s -o service

FROM alpine:3.20
RUN apk --no-cache add ca-certificates
WORKDIR /app
COPY --from=builder /app/service .
CMD ["./service"]
`, srvFile)

	railwayPath := filepath.Join(targetDir, "railway.json")
	dockerPath := filepath.Join(targetDir, "Dockerfile")

	if err := os.WriteFile(railwayPath, []byte(railwayJSON), 0644); err != nil {
		fmt.Printf("Failed to write railway.json: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(dockerPath, []byte(dockerfile), 0644); err != nil {
		fmt.Printf("Failed to write Dockerfile: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("✓ Generated railway.json and Dockerfile for '%s'\n", appName)
	fmt.Println("\nNext steps:")
	fmt.Println("  1. Install Railway CLI: https://docs.railway.app/guides/cli")
	fmt.Println("  2. railway login")
	fmt.Println("  3. railway init")
	fmt.Println("  4. railway up")
}

func generateRenderConfig(targetDir, appName, port, srvFile string) {
	renderYAML := fmt.Sprintf(`# Generated by: serv deploy --target render
services:
  - type: web
    name: %s
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "%s"
`, appName, port)

	dockerfile := fmt.Sprintf(`FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY . .
RUN go build -o serv.exe .
RUN ./serv.exe build %s -o service

FROM alpine:3.20
RUN apk --no-cache add ca-certificates
WORKDIR /app
COPY --from=builder /app/service .
EXPOSE %s
CMD ["./service"]
`, srvFile, port)

	renderPath := filepath.Join(targetDir, "render.yaml")
	dockerPath := filepath.Join(targetDir, "Dockerfile")

	if err := os.WriteFile(renderPath, []byte(renderYAML), 0644); err != nil {
		fmt.Printf("Failed to write render.yaml: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(dockerPath, []byte(dockerfile), 0644); err != nil {
		fmt.Printf("Failed to write Dockerfile: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("✓ Generated render.yaml and Dockerfile for '%s'\n", appName)
	fmt.Println("\nNext steps:")
	fmt.Println("  1. Push to GitHub")
	fmt.Println("  2. Connect the repo on https://dashboard.render.com")
	fmt.Println("  3. Render auto-detects render.yaml and deploys")
}
