package main

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"serv/compiler"
)

func runTests(srvFile string, withCoverage bool) {
	absPath, program, err := parseProject(srvFile)
	if err != nil {
		fmt.Printf("Parse error: %v\n", err)
		os.Exit(1)
	}

	cg := compiler.NewCodegen(program)
	goCode, err := cg.Generate()
	if err != nil {
		fmt.Printf("Codegen error: %v\n", err)
		os.Exit(1)
	}

	if !cg.HasTests() {
		fmt.Println("No tests found in", srvFile)
		return
	}

	buildDir := buildDirFor(absPath)
	if err := os.MkdirAll(buildDir, 0755); err != nil {
		fmt.Printf("Failed to create build dir: %v\n", err)
		os.Exit(1)
	}

	// Clean stale Go files from previous builds to prevent conflicts
	for _, name := range []string{"main.go", "service.go", "serv_test.go", "coverage.out"} {
		_ = os.Remove(filepath.Join(buildDir, name))
	}

	// Write service.go: all generated declarations (functions, init blocks, etc.)
	serviceCode := goCode + "\n" + cg.GenerateHelpers()
	if err := os.WriteFile(filepath.Join(buildDir, "service.go"), []byte(serviceCode), 0644); err != nil {
		fmt.Printf("Failed to write service.go: %v\n", err)
		os.Exit(1)
	}

	// Write a minimal main.go stub (go test needs a package main with a main func)
	mainStub := "// Code generated by Serv compiler. DO NOT EDIT.\npackage main\n\nfunc main() {}\n"
	if err := os.WriteFile(filepath.Join(buildDir, "main.go"), []byte(mainStub), 0644); err != nil {
		fmt.Printf("Failed to write main.go: %v\n", err)
		os.Exit(1)
	}

	// Write serv_test.go
	testCode := cg.GenerateTests()
	testFile := filepath.Join(buildDir, "serv_test.go")
	if err := os.WriteFile(testFile, []byte(testCode), 0644); err != nil {
		fmt.Printf("Failed to write test file: %v\n", err)
		os.Exit(1)
	}

	// Ensure the build directory has a go.mod that can find serv/runtime
	goModChanged, err := ensureBuildGoMod(buildDir)
	if err != nil {
		fmt.Printf("Failed to setup build module: %v\n", err)
		os.Exit(1)
	}
	if goModChanged {
		if err := runGoModTidy(buildDir); err != nil {
			fmt.Printf("Failed to tidy build module: %v\n", err)
			os.Exit(1)
		}
	}

	fmt.Printf("Running tests from %s...\n", srvFile)
	goPath, err := resolveGoPath()
	if err != nil {
		fmt.Printf("Cannot find Go compiler: %v\n", err)
		os.Exit(1)
	}

	// Build go test command with appropriate flags
	testArgs := []string{"test", "-v"}
	if withCoverage {
		coverFile := filepath.Join(buildDir, "coverage.out")
		testArgs = append(testArgs, "-coverprofile="+coverFile)
	}
	testArgs = append(testArgs, "./...")

	cmd := exec.Command(goPath, testArgs...)
	cmd.Dir = buildDir
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	testErr := cmd.Run()

	// Show coverage summary if requested
	if withCoverage {
		coverFile := filepath.Join(buildDir, "coverage.out")
		if _, statErr := os.Stat(coverFile); statErr == nil {
			fmt.Println()
			fmt.Println("--- Coverage ---")
			coverCmd := exec.Command(goPath, "tool", "cover", "-func="+coverFile)
			coverCmd.Dir = buildDir
			var coverOut bytes.Buffer
			coverCmd.Stdout = &coverOut
			coverCmd.Stderr = os.Stderr
			if err := coverCmd.Run(); err == nil {
				// Extract just the total line
				lines := strings.Split(coverOut.String(), "\n")
				for _, line := range lines {
					if strings.Contains(line, "total:") {
						fmt.Println(strings.TrimSpace(line))
					}
				}
			}
			fmt.Printf("Coverage profile: %s\n", coverFile)
		}
	}

	if testErr != nil {
		fmt.Printf("Tests failed: %v\n", testErr)
		os.Exit(1)
	}
}
