package main

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

type goDocFunc struct {
	name        string
	params      string
	returnType  string
	multiReturn bool // true if function returns (value, error)
}

// addPackage generates a .srv.d declaration file for a Go package.
func addPackage(pkgPath string) {
	// Run go doc to get package documentation
	goPath, err := resolveGoPath()
	if err != nil {
		fmt.Printf("Cannot find Go compiler: %v\n", err)
		os.Exit(1)
	}

	// Step 1: Try to go get the package first (add to go.mod)
	fmt.Printf("Fetching %s...\n", pkgPath)
	getCmd := exec.Command(goPath, "get", pkgPath)
	getCmd.Stderr = os.Stderr
	if err := getCmd.Run(); err != nil {
		// Not fatal — package might already be available (stdlib)
		fmt.Printf("Note: go get %s returned an error (may already be available)\n", pkgPath)
	}

	// Step 2: Run go doc to extract function signatures
	cmd := exec.Command(goPath, "doc", "-all", pkgPath)
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	if err := cmd.Run(); err != nil {
		fmt.Printf("Failed to get package info for %s: %v\n%s\n", pkgPath, err, stderr.String())
		fmt.Println("Make sure the package is available: go get", pkgPath)
		os.Exit(1)
	}

	// Step 3: Parse the go doc output to extract exported functions
	output := stdout.String()
	functions := parseGoDocFunctions(output)

	if len(functions) == 0 {
		fmt.Printf("No exported functions found in %s\n", pkgPath)
		os.Exit(1)
	}

	// Step 4: Generate .srv.d file
	pkgName := filepath.Base(pkgPath)
	declDir := "declarations"
	os.MkdirAll(declDir, 0755)

	var content strings.Builder
	content.WriteString(fmt.Sprintf("// Auto-generated declaration for %s\n", pkgPath))
	content.WriteString(fmt.Sprintf("// Generated by: serv add %s\n\n", pkgPath))
	content.WriteString(fmt.Sprintf("declare module \"%s\" {\n", pkgPath))
	for _, fn := range functions {
		if fn.multiReturn {
			content.WriteString(fmt.Sprintf("    fn! %s(%s)", fn.name, fn.params))
		} else {
			content.WriteString(fmt.Sprintf("    fn %s(%s)", fn.name, fn.params))
		}
		if fn.returnType != "" {
			content.WriteString(fmt.Sprintf(" -> %s", fn.returnType))
		}
		content.WriteString("\n")
	}
	content.WriteString("}\n")

	declFile := filepath.Join(declDir, pkgName+".srv.d")
	if err := os.WriteFile(declFile, []byte(content.String()), 0644); err != nil {
		fmt.Printf("Failed to write declaration file: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("✓ Generated declaration: %s (%d functions)\n", declFile, len(functions))
	fmt.Printf("\nUsage in your .srv file:\n")
	fmt.Printf("  import %s from \"%s\"\n", pkgName, pkgPath)
	fmt.Printf("  let result = %s.FunctionName(args)\n", pkgName)
}

// listPackages shows all installed declaration files.
func listPackages() {
	declDir := "declarations"
	entries, err := os.ReadDir(declDir)
	if err != nil {
		fmt.Println("No packages installed yet. Use: serv add <package>")
		return
	}

	fmt.Println("Installed packages:")
	fmt.Println()
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".srv.d") {
			name := strings.TrimSuffix(e.Name(), ".srv.d")
			// Read first two lines to get the package path
			content, _ := os.ReadFile(filepath.Join(declDir, e.Name()))
			lines := strings.Split(string(content), "\n")
			pkgPath := name
			for _, line := range lines {
				if strings.Contains(line, "declare module") {
					start := strings.Index(line, "\"")
					end := strings.LastIndex(line, "\"")
					if start >= 0 && end > start {
						pkgPath = line[start+1 : end]
					}
					break
				}
			}
			fmt.Printf("  %-20s %s\n", name, pkgPath)
		}
	}
}

// removePackage deletes a declaration file.
func removePackage(name string) {
	declDir := "declarations"
	declFile := filepath.Join(declDir, name+".srv.d")
	if _, err := os.Stat(declFile); os.IsNotExist(err) {
		fmt.Printf("Package '%s' not found in declarations/\n", name)
		fmt.Println("Use: serv packages — to see installed packages")
		os.Exit(1)
	}
	if err := os.Remove(declFile); err != nil {
		fmt.Printf("Failed to remove %s: %v\n", declFile, err)
		os.Exit(1)
	}
	fmt.Printf("✓ Removed package: %s\n", name)
}

func parseGoDocFunctions(doc string) []goDocFunc {
	var functions []goDocFunc
	lines := strings.Split(doc, "\n")

	for _, line := range lines {
		line = strings.TrimSpace(line)
		// Match: func FuncName(params) returnType
		if !strings.HasPrefix(line, "func ") {
			continue
		}
		// Skip methods (have a receiver)
		trimmed := strings.TrimPrefix(line, "func ")
		if strings.HasPrefix(trimmed, "(") {
			continue // method with receiver
		}

		// Extract function name
		parenIdx := strings.Index(trimmed, "(")
		if parenIdx < 0 {
			continue
		}
		funcName := trimmed[:parenIdx]

		// Extract params and return type
		rest := trimmed[parenIdx:]
		// Find matching closing paren
		depth := 0
		closeIdx := -1
		for i, ch := range rest {
			if ch == '(' {
				depth++
			} else if ch == ')' {
				depth--
				if depth == 0 {
					closeIdx = i
					break
				}
			}
		}
		if closeIdx < 0 {
			continue
		}

		paramsRaw := rest[1:closeIdx]
		returnRaw := strings.TrimSpace(rest[closeIdx+1:])

		// Simplify params to Serv types
		params := simplifyGoParams(paramsRaw)
		returnType := simplifyGoType(returnRaw)

		functions = append(functions, goDocFunc{
			name:        funcName,
			params:      params,
			returnType:  returnType,
			multiReturn: isMultiReturn(returnRaw),
		})
	}
	return functions
}

func simplifyGoParams(raw string) string {
	if raw == "" {
		return ""
	}
	parts := strings.Split(raw, ",")
	var result []string
	for _, p := range parts {
		p = strings.TrimSpace(p)
		tokens := strings.Fields(p)
		if len(tokens) >= 2 {
			name := tokens[0]
			goType := strings.Join(tokens[1:], " ")
			srvType := goTypeToServType(goType)
			result = append(result, name+": "+srvType)
		} else if len(tokens) == 1 {
			result = append(result, tokens[0])
		}
	}
	return strings.Join(result, ", ")
}

func simplifyGoType(raw string) string {
	raw = strings.TrimSpace(raw)
	// Remove parentheses from multi-return
	raw = strings.TrimPrefix(raw, "(")
	raw = strings.TrimSuffix(raw, ")")
	if raw == "" {
		return ""
	}
	// For multi-return, just take the first type
	parts := strings.Split(raw, ",")
	return goTypeToServType(strings.TrimSpace(parts[0]))
}

func isMultiReturn(raw string) bool {
	raw = strings.TrimSpace(raw)
	return strings.HasPrefix(raw, "(") && strings.Contains(raw, ",")
}

func goTypeToServType(goType string) string {
	goType = strings.TrimSpace(goType)
	switch goType {
	case "string":
		return "string"
	case "int", "int64", "int32", "uint", "uint64":
		return "int"
	case "float64", "float32":
		return "float"
	case "bool":
		return "bool"
	case "error":
		return "string"
	case "[]byte":
		return "string"
	default:
		if strings.HasPrefix(goType, "[]") {
			return "[]" + goTypeToServType(strings.TrimPrefix(goType, "[]"))
		}
		return "string" // default fallback
	}
}

func getRegistryURL() string {
	url := os.Getenv("SERV_REGISTRY")
	if url == "" {
		url = "https://registry.serv-lang.org"
	}
	return strings.TrimSuffix(url, "/")
}

func installPackage(pkgName string) {
	registry := getRegistryURL()
	url := fmt.Sprintf("%s/packages/%s.tar.gz", registry, pkgName)
	fmt.Printf("Downloading package from %s...\n", url)
	resp, err := http.Get(url)
	if err != nil {
		fmt.Printf("Error connecting to registry: %v\n", err)
		os.Exit(1)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		fmt.Printf("Registry returned status %d\n", resp.StatusCode)
		os.Exit(1)
	}

	// Untar into packages/pkgName
	targetDir := filepath.Join("packages", pkgName)
	if err := os.MkdirAll(targetDir, 0755); err != nil {
		fmt.Printf("Failed to create package directory: %v\n", err)
		os.Exit(1)
	}

	gr, err := gzip.NewReader(resp.Body)
	if err != nil {
		fmt.Printf("Failed to initialize gzip reader: %v\n", err)
		os.Exit(1)
	}
	defer gr.Close()

	tr := tar.NewReader(gr)
	for {
		hdr, err := tr.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			fmt.Printf("Failed to read tar header: %v\n", err)
			os.Exit(1)
		}

		// Prevent Zip Slip / path traversal
		cleaned := filepath.Clean(hdr.Name)
		if strings.HasPrefix(cleaned, "..") || strings.HasPrefix(cleaned, "/") {
			continue
		}

		dest := filepath.Join(targetDir, cleaned)
		switch hdr.Typeflag {
		case tar.TypeDir:
			os.MkdirAll(dest, 0755)
		case tar.TypeReg:
			os.MkdirAll(filepath.Dir(dest), 0755)
			f, err := os.OpenFile(dest, os.O_CREATE|os.O_RDWR|os.O_TRUNC, os.FileMode(hdr.Mode))
			if err != nil {
				fmt.Printf("Failed to create file %s: %v\n", dest, err)
				os.Exit(1)
			}
			if _, err := io.Copy(f, tr); err != nil {
				f.Close()
				fmt.Printf("Failed to write file %s: %v\n", dest, err)
				os.Exit(1)
			}
			f.Close()
		}
	}

	fmt.Printf("✓ Package '%s' successfully installed to %s/\n", pkgName, targetDir)
}

func publishPackage(pkgDir string) {
	// Create in-memory tar.gz
	var buf bytes.Buffer
	gw := gzip.NewWriter(&buf)
	tw := tar.NewWriter(gw)

	absPkgDir, err := filepath.Abs(pkgDir)
	if err != nil {
		fmt.Printf("Invalid package directory: %v\n", err)
		os.Exit(1)
	}

	err = filepath.Walk(absPkgDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		// Compute relative path
		relPath, err := filepath.Rel(absPkgDir, path)
		if err != nil {
			return err
		}
		if relPath == "." {
			return nil
		}

		hdr, err := tar.FileInfoHeader(info, "")
		if err != nil {
			return err
		}
		hdr.Name = filepath.ToSlash(relPath)

		if err := tw.WriteHeader(hdr); err != nil {
			return err
		}

		if info.Mode().IsRegular() {
			f, err := os.Open(path)
			if err != nil {
				return err
			}
			defer f.Close()
			if _, err := io.Copy(tw, f); err != nil {
				return err
			}
		}
		return nil
	})

	if err != nil {
		fmt.Printf("Failed to package files: %v\n", err)
		os.Exit(1)
	}

	tw.Close()
	gw.Close()

	// Send HTTP POST to registry
	registry := getRegistryURL()
	url := fmt.Sprintf("%s/publish?name=%s", registry, filepath.Base(absPkgDir))
	fmt.Printf("Publishing package to %s...\n", url)

	req, err := http.NewRequest("POST", url, &buf)
	if err != nil {
		fmt.Printf("Failed to create publish request: %v\n", err)
		os.Exit(1)
	}
	req.Header.Set("Content-Type", "application/octet-stream")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		fmt.Printf("Publish failed: %v\n", err)
		os.Exit(1)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK && resp.StatusCode != http.StatusCreated {
		bodyBytes, _ := io.ReadAll(resp.Body)
		fmt.Printf("Publish failed with status %d: %s\n", resp.StatusCode, string(bodyBytes))
		os.Exit(1)
	}

	fmt.Printf("✓ Package '%s' successfully published!\n", filepath.Base(absPkgDir))
}
