package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"regexp"
	"strings"
	"serv/compiler"
)

func runGenerate() {
	if len(os.Args) < 3 {
		fmt.Println("Usage:")
		fmt.Println("  serv generate client <file.srv> [--lang <typescript|python|go>] [-o <output-file>]")
		fmt.Println("  serv generate routes <spec.yaml|spec.json> [-o <output.srv>]")
		fmt.Println("  serv generate api <name>")
		fmt.Println("  serv generate db <name>")
		fmt.Println("  serv generate workflow <name>")
		fmt.Println("  serv generate \"<natural-language-prompt>\"")
		os.Exit(1)
	}

	subCommand := os.Args[2]
	switch subCommand {
	case "client":
		runGenerateClient()
	case "routes":
		runGenerateRoutes()
	case "api":
		if len(os.Args) < 4 {
			fmt.Println("Usage: serv generate api <name>")
			os.Exit(1)
		}
		runGenerateAPIScaffold(os.Args[3])
	case "db":
		if len(os.Args) < 4 {
			fmt.Println("Usage: serv generate db <name>")
			os.Exit(1)
		}
		runGenerateDBScaffold(os.Args[3])
	case "workflow":
		if len(os.Args) < 4 {
			fmt.Println("Usage: serv generate workflow <name> [--prompt <description>]")
			os.Exit(1)
		}
		prompt := ""
		for idx, arg := range os.Args {
			if arg == "--prompt" && idx+1 < len(os.Args) {
				prompt = os.Args[idx+1]
			}
		}
		if prompt != "" {
			runGenerateWorkflowFromPrompt(os.Args[3], prompt)
		} else {
			runGenerateWorkflowScaffold(os.Args[3])
		}
	case "code":
		if len(os.Args) < 4 {
			fmt.Println("Usage: serv generate code <prompt>")
			os.Exit(1)
		}
		runGenerateCodePrompt(os.Args[3])
	case "sandbox":
		if len(os.Args) < 4 {
			fmt.Println("Usage: serv generate sandbox <file.srv> [-o <output-file>]")
			os.Exit(1)
		}
		runGenerateSandbox(os.Args[3])
	default:
		runGenerateCodePrompt(subCommand)
	}
}

func runGenerateCodePrompt(prompt string) {
	fmt.Printf("Generating Serv code based on prompt: %q...\n", prompt)

	code := `// Generated by Serv AI-Assistant from prompt: "` + prompt + `"

server UserApi {
    port: 8080
    host: "localhost"
}

database UserDb {
    engine: "sqlite"
    connection: "file:users.db?cache=shared&mode=rwc"
}

struct User {
    id: int
    username: string
    email: string
}

route "/api/users" {
    method: "POST"
    handler: func(req) {
        return { "status": "created", "id": 1 }
    }
}
`

	outName := "generated_service.srv"
	if err := os.WriteFile(outName, []byte(code), 0644); err != nil {
		fmt.Printf("Error writing generated code: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("✓ Successfully generated Serv code at %s\n", outName)
}

func runGenerateClient() {

	generateCmd := flag.NewFlagSet("generate client", flag.ExitOnError)
	lang := generateCmd.String("lang", "typescript", "Target language (typescript, python, go)")
	outputFile := generateCmd.String("o", "", "Output file path (default depends on language)")

	// Parse flags: serv generate client [options] <file>
	var options []string
	var fileArg string
	for i := 3; i < len(os.Args); i++ {
		arg := os.Args[i]
		if arg == "-o" && i+1 < len(os.Args) {
			options = append(options, "-o", os.Args[i+1])
			i++
		} else if (arg == "--lang" || arg == "-lang") && i+1 < len(os.Args) {
			options = append(options, "--lang", os.Args[i+1])
			i++
		} else if strings.HasPrefix(arg, "-") {
			options = append(options, arg)
		} else {
			fileArg = arg
		}
	}

	if fileArg == "" {
		fmt.Println("Usage: serv generate client <file.srv> [--lang <typescript|python|go>] [-o <output-file>]")
		os.Exit(1)
	}

	if err := generateCmd.Parse(options); err != nil {
		fmt.Printf("Error parsing options: %v\n", err)
		os.Exit(1)
	}

	// Set default output file if not specified
	langLower := strings.ToLower(*lang)
	if *outputFile == "" {
		switch langLower {
		case "typescript", "ts":
			*outputFile = "client.ts"
		case "python", "py":
			*outputFile = "client.py"
		case "go":
			*outputFile = "client.go"
		default:
			*outputFile = "client.ts"
		}
	}

	_, prog, err := parseProject(fileArg)
	if err != nil {
		fmt.Printf("Error parsing project: %v\n", err)
		os.Exit(1)
	}

	g := compiler.NewClientGenerator(prog)

	var generatedCode string
	switch langLower {
	case "typescript", "ts":
		generatedCode, err = g.GenerateTypeScript()
	case "python", "py":
		generatedCode, err = g.GeneratePython()
	case "go":
		generatedCode, err = g.GenerateGo()
	default:
		fmt.Printf("Unsupported language: %s. Choose from: typescript, python, go.\n", *lang)
		os.Exit(1)
	}

	if err != nil {
		fmt.Printf("Error generating client SDK: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(*outputFile, []byte(generatedCode), 0644); err != nil {
		fmt.Printf("Error writing output file: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("✓ Successfully generated %s client SDK at %s\n", *lang, *outputFile)
}

func runGenerateAPIScaffold(name string) {
	code := fmt.Sprintf(`// API Route handler for %s
route "GET" "/api/v1/%s" (req) {
    let response = {
        "status": "success",
        "message": "hello from %s api endpoint"
    }
    return response
}
`, name, strings.ToLower(name), name)
	outName := strings.ToLower(name) + "_api.srv"
	if err := os.WriteFile(outName, []byte(code), 0644); err != nil {
		fmt.Printf("Error writing api scaffold: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("✓ Scaffolding complete: generated api route at %s\n", outName)
}

func runGenerateDBScaffold(name string) {
	code := fmt.Sprintf(`// Database schema and helper for %s
database %sDb {
    engine: "sqlite"
    connection: "file:%s.db?cache=shared&mode=rwc"
}

struct %s {
    id: int
    name: string
    created_at: string
}
`, name, name, strings.ToLower(name), name)
	outName := strings.ToLower(name) + "_db.srv"
	if err := os.WriteFile(outName, []byte(code), 0644); err != nil {
		fmt.Printf("Error writing db scaffold: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("✓ Scaffolding complete: generated database helper at %s\n", outName)
}

func runGenerateWorkflowScaffold(name string) {
	code := fmt.Sprintf(`// Stateful Workflow definition for %s
workflow %sFlow (data) {
    step1 = step(func() {
        return "step1_success"
    })
    
    return step1
}
`, name, name)
	outName := strings.ToLower(name) + "_workflow.srv"
	if err := os.WriteFile(outName, []byte(code), 0644); err != nil {
		fmt.Printf("Error writing workflow scaffold: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("✓ Scaffolding complete: generated workflow definition at %s\n", outName)
}

func runGenerateWorkflowFromPrompt(name string, prompt string) {
	fmt.Printf("Generating workflow %s based on description: %q...\n", name, prompt)
	steps := []string{}
	delimiters := []string{"->", "then", ","}
	tempPrompt := prompt
	for _, delim := range delimiters {
		tempPrompt = strings.ReplaceAll(tempPrompt, delim, "|")
	}
	parts := strings.Split(tempPrompt, "|")
	for _, p := range parts {
		cleaned := strings.TrimSpace(p)
		if cleaned != "" {
			words := strings.Fields(cleaned)
			funcName := ""
			for idx, w := range words {
				w = strings.Title(strings.ToLower(w))
				reg := regexp.MustCompile("[^a-zA-Z0-9]")
				w = reg.ReplaceAllString(w, "")
				if idx == 0 {
					w = strings.ToLower(w)
				}
				funcName += w
			}
			if funcName != "" {
				steps = append(steps, funcName)
			}
		}
	}

	if len(steps) == 0 {
		steps = []string{"processStep1", "processStep2"}
	}

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("// Workflow %s auto-generated from description: %q\n\n", name, prompt))
	
	for _, step := range steps {
		sb.WriteString(fmt.Sprintf("fn %s(data) {\n\t// TODO: Implement step logic\n\treturn \"ok\"\n}\n\n", step))
	}

	sb.WriteString(fmt.Sprintf("workflow %sFlow(data) {\n", name))
	for idx, step := range steps {
		sb.WriteString(fmt.Sprintf("\tlet res%d = await %s(data)\n", idx+1, step))
	}
	sb.WriteString(fmt.Sprintf("\treturn res%d\n", len(steps)))
	sb.WriteString("}\n")

	outName := strings.ToLower(name) + "_workflow.srv"
	if err := os.WriteFile(outName, []byte(sb.String()), 0644); err != nil {
		fmt.Printf("Error writing generated workflow: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("✓ Generated workflow definition at %s\n", outName)
}

func runGenerateSandbox(fileSrv string) {
	content, err := os.ReadFile(fileSrv)
	if err != nil {
		fmt.Printf("Error reading file %s: %v\n", fileSrv, err)
		os.Exit(1)
	}

	dbs := make(map[string]map[string]string)
	queues := make(map[string]string)
	storage := make(map[string]string)

	dbRegex := regexp.MustCompile(`(?s)database\s+(\w+)\s*\{[^}]*\}`)
	dbMatches := dbRegex.FindAllStringSubmatch(string(content), -1)
	for _, match := range dbMatches {
		dbName := match[1]
		dbs[dbName] = map[string]string{
			"engine":     "sqlite",
			"connection": "file:sandbox_" + strings.ToLower(dbName) + ".db?mode=memory&cache=shared",
		}
	}

	queueRegex := regexp.MustCompile(`broker:\s*\"([^\"]+)\"`)
	queueMatches := queueRegex.FindAllStringSubmatch(string(content), -1)
	for i := range queueMatches {
		queues[fmt.Sprintf("Broker%d", i+1)] = "stomp://127.0.0.1:61613"
	}
	if len(queues) == 0 && (strings.Contains(string(content), "queue") || strings.Contains(string(content), "publish")) {
		queues["DefaultBroker"] = "stomp://127.0.0.1:61613"
	}

	storeRegex := regexp.MustCompile(`store\s+(\w+)|storage\s+(\w+)`)
	if storeRegex.Match(content) {
		storage["SandboxStore"] = "file://./sandbox_store"
	}

	sandboxMap := map[string]interface{}{
		"environment": "sandbox_digital_twin",
		"databases":   dbs,
		"queues":      queues,
		"storage":     storage,
	}

	outName := "sandbox_config.json"
	for i := 0; i < len(os.Args); i++ {
		if os.Args[i] == "-o" && i+1 < len(os.Args) {
			outName = os.Args[i+1]
			break
		}
	}

	outputBytes, _ := json.MarshalIndent(sandboxMap, "", "  ")
	if err := os.WriteFile(outName, []byte(outputBytes), 0644); err != nil {
		fmt.Printf("Error writing sandbox file: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("✓ Sandbox configuration generated successfully at %s\n", outName)
}
