package tabs

import (
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
)

type DesignerNode struct {
	ID    string `json:"id"`
	Type  string `json:"type"`
	Label string `json:"label"`
}

type DesignerLink struct {
	Source string `json:"source"`
	Target string `json:"target"`
}

type DesignerTopology struct {
	Nodes []DesignerNode `json:"nodes"`
	Links []DesignerLink `json:"links"`
}

type StudioProject struct {
	Name string `json:"name"`
	Path string `json:"path"`
}

type BreakpointState struct {
	File      string                 `json:"file"`
	Line      int                    `json:"line"`
	Variables map[string]interface{} `json:"variables"`
	Hit       bool                   `json:"hit"`
}

func HandleDesignerLayout(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	if r.Method != http.MethodPost && r.Method != http.MethodGet {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	layout := DesignerTopology{
		Nodes: []DesignerNode{
			{ID: "gate", Type: "service", Label: "ServGate Proxy"},
			{ID: "store", Type: "database", Label: "ServStore Object Store"},
			{ID: "queue", Type: "queue", Label: "ServQueue Broker"},
		},
		Links: []DesignerLink{
			{Source: "gate", Target: "store"},
			{Source: "gate", Target: "queue"},
		},
	}
	json.NewEncoder(w).Encode(layout)
}

func HandleDesignerSync(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	if r.Method != http.MethodPost {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	var topo DesignerTopology
	if err := json.NewDecoder(r.Body).Decode(&topo); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	var srvCode strings.Builder
	srvCode.WriteString("// Autogenerated from Visual Architecture Designer\n\n")
	for _, node := range topo.Nodes {
		if node.Type == "service" {
			srvCode.WriteString(fmt.Sprintf("service %s {\n\t// TODO: implement service logic\n}\n\n", node.ID))
		}
	}

	w.WriteHeader(http.StatusOK)
	json.NewEncoder(w).Encode(map[string]interface{}{
		"status": "synchronized",
		"code":   srvCode.String(),
	})
}

func HandleStudioProjects(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	if r.Method != http.MethodGet {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	projects := []StudioProject{
		{Name: "Servverse Project", Path: "c:/Mine/try/serv/Serv-Project"},
	}
	json.NewEncoder(w).Encode(projects)
}

func HandleStudioDebug(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	if r.Method != http.MethodPost {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	var req struct {
		Action string `json:"action"`
		File   string `json:"file"`
		Line   int    `json:"line"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	state := BreakpointState{
		File: req.File,
		Line: req.Line,
		Variables: map[string]interface{}{
			"tenant_id": "T-100",
			"user_role": "admin",
			"request":   "GET /healthz",
		},
		Hit: true,
	}

	w.WriteHeader(http.StatusOK)
	json.NewEncoder(w).Encode(state)
}
