package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// OpenAPI minimal types for route generation
type openAPISpec struct {
	OpenAPI string                      `json:"openapi" yaml:"openapi"`
	Info    openAPIInfo                 `json:"info" yaml:"info"`
	Paths   map[string]openAPIPathItem `json:"paths" yaml:"paths"`
}

type openAPIInfo struct {
	Title   string `json:"title" yaml:"title"`
	Version string `json:"version" yaml:"version"`
}

type openAPIPathItem map[string]openAPIOperation // method -> operation

type openAPIOperation struct {
	Summary     string                     `json:"summary" yaml:"summary"`
	OperationID string                     `json:"operationId" yaml:"operationId"`
	Parameters  []openAPIParameter         `json:"parameters" yaml:"parameters"`
	RequestBody *openAPIRequestBody        `json:"requestBody" yaml:"requestBody"`
	Responses   map[string]openAPIResponse `json:"responses" yaml:"responses"`
	Tags        []string                   `json:"tags" yaml:"tags"`
}

type openAPIParameter struct {
	Name     string `json:"name" yaml:"name"`
	In       string `json:"in" yaml:"in"` // path, query, header
	Required bool   `json:"required" yaml:"required"`
	Schema   *openAPISchema `json:"schema" yaml:"schema"`
}

type openAPIRequestBody struct {
	Required bool                          `json:"required" yaml:"required"`
	Content  map[string]openAPIMediaType   `json:"content" yaml:"content"`
}

type openAPIMediaType struct {
	Schema *openAPISchema `json:"schema" yaml:"schema"`
}

type openAPIResponse struct {
	Description string `json:"description" yaml:"description"`
}

type openAPISchema struct {
	Type       string                    `json:"type" yaml:"type"`
	Properties map[string]openAPISchema  `json:"properties" yaml:"properties"`
	Items      *openAPISchema            `json:"items" yaml:"items"`
	Ref        string                    `json:"$ref" yaml:"$ref"`
}

func runGenerateRoutes() {
	genCmd := flag.NewFlagSet("generate routes", flag.ExitOnError)
	outputFile := genCmd.String("o", "", "Output .srv file path (default: routes.srv)")
	serverURL := genCmd.String("server", "8080", "Server port or URL for the generated service")
	dbURL := genCmd.String("db", "", "Database connection string (e.g., sqlite://app.db)")

	var options []string
	var specFile string
	for i := 3; i < len(os.Args); i++ {
		arg := os.Args[i]
		if (arg == "-o" || arg == "--server" || arg == "--db") && i+1 < len(os.Args) {
			options = append(options, arg, os.Args[i+1])
			i++
		} else if strings.HasPrefix(arg, "-") {
			options = append(options, arg)
		} else {
			specFile = arg
		}
	}

	if specFile == "" {
		fmt.Println("Usage: serv generate routes <spec.yaml|spec.json> [-o <output.srv>] [--server <port>] [--db <dsn>]")
		os.Exit(1)
	}

	if err := genCmd.Parse(options); err != nil {
		fmt.Printf("Error parsing options: %v\n", err)
		os.Exit(1)
	}

	if *outputFile == "" {
		base := strings.TrimSuffix(filepath.Base(specFile), filepath.Ext(specFile))
		*outputFile = base + ".srv"
	}

	// Read and parse the spec
	data, err := os.ReadFile(specFile)
	if err != nil {
		fmt.Printf("Error reading spec file: %v\n", err)
		os.Exit(1)
	}

	var spec openAPISpec
	ext := strings.ToLower(filepath.Ext(specFile))
	if ext == ".json" {
		err = json.Unmarshal(data, &spec)
	} else {
		err = yaml.Unmarshal(data, &spec)
	}
	if err != nil {
		fmt.Printf("Error parsing OpenAPI spec: %v\n", err)
		os.Exit(1)
	}

	if len(spec.Paths) == 0 {
		fmt.Println("No paths found in the OpenAPI spec.")
		os.Exit(1)
	}

	// Generate .srv code
	code := generateSrvFromSpec(&spec, *serverURL, *dbURL)

	if err := os.WriteFile(*outputFile, []byte(code), 0644); err != nil {
		fmt.Printf("Error writing output file: %v\n", err)
		os.Exit(1)
	}

	routeCount := countRoutes(spec.Paths)
	fmt.Printf("✓ Generated %d routes from %s → %s\n", routeCount, specFile, *outputFile)
	fmt.Printf("  Title: %s (v%s)\n", spec.Info.Title, spec.Info.Version)
}

func generateSrvFromSpec(spec *openAPISpec, serverURL, dbURL string) string {
	var b strings.Builder

	// Header
	b.WriteString(fmt.Sprintf("// Generated from OpenAPI spec: %s v%s\n", spec.Info.Title, spec.Info.Version))
	b.WriteString("// Auto-generated by: serv generate routes\n")
	b.WriteString("// Edit this file to add business logic to the route handlers.\n\n")

	// Server declaration
	b.WriteString(fmt.Sprintf("server \"%s\"\n", serverURL))

	// Database (if specified)
	if dbURL != "" {
		b.WriteString(fmt.Sprintf("database \"%s\"\n", dbURL))
	}
	b.WriteString("\n")

	// Sort paths for deterministic output
	paths := make([]string, 0, len(spec.Paths))
	for path := range spec.Paths {
		paths = append(paths, path)
	}
	sort.Strings(paths)

	// Generate routes
	for _, path := range paths {
		pathItem := spec.Paths[path]
		methods := []string{"get", "post", "put", "patch", "delete"}
		for _, method := range methods {
			op, exists := pathItem[method]
			if !exists {
				continue
			}
			generateRoute(&b, method, path, &op)
		}
	}

	return b.String()
}

func generateRoute(b *strings.Builder, method, path string, op *openAPIOperation) {
	// Convert OpenAPI path params {id} → Serv-lang :id
	srvPath := convertPath(path)
	httpMethod := strings.ToUpper(method)

	// Comment with summary
	if op.Summary != "" {
		b.WriteString(fmt.Sprintf("// %s\n", op.Summary))
	}
	if op.OperationID != "" {
		b.WriteString(fmt.Sprintf("// operationId: %s\n", op.OperationID))
	}

	// Route declaration
	b.WriteString(fmt.Sprintf("route \"%s\" \"%s\" (req) {\n", httpMethod, srvPath))

	// Extract path params
	for _, param := range op.Parameters {
		if param.In == "path" {
			b.WriteString(fmt.Sprintf("    let %s = req.params.%s\n", param.Name, param.Name))
		}
	}

	// Extract query params
	queryParams := []openAPIParameter{}
	for _, param := range op.Parameters {
		if param.In == "query" {
			queryParams = append(queryParams, param)
		}
	}
	if len(queryParams) > 0 {
		for _, param := range queryParams {
			b.WriteString(fmt.Sprintf("    let %s = req.params.%s\n", param.Name, param.Name))
		}
	}

	// Parse body for POST/PUT/PATCH
	if op.RequestBody != nil && (method == "post" || method == "put" || method == "patch") {
		b.WriteString("    let body = json.parse(req.body)\n")

		// Extract fields from schema if available
		if op.RequestBody.Content != nil {
			if mediaType, ok := op.RequestBody.Content["application/json"]; ok && mediaType.Schema != nil {
				if mediaType.Schema.Properties != nil {
					for field := range mediaType.Schema.Properties {
						b.WriteString(fmt.Sprintf("    let %s = body.%s\n", field, field))
					}
				}
			}
		}
		b.WriteString("\n")
	}

	// Placeholder response
	b.WriteString("    // TODO: implement business logic\n")

	// Generate response based on method
	switch method {
	case "get":
		b.WriteString("    return { \"data\": [] }\n")
	case "post":
		b.WriteString("    return { \"created\": true }\n")
	case "put", "patch":
		b.WriteString("    return { \"updated\": true }\n")
	case "delete":
		b.WriteString("    return { \"deleted\": true }\n")
	default:
		b.WriteString("    return { \"ok\": true }\n")
	}

	b.WriteString("}\n\n")
}

func convertPath(openAPIPath string) string {
	// Convert {param} to :param
	result := openAPIPath
	for {
		start := strings.Index(result, "{")
		if start == -1 {
			break
		}
		end := strings.Index(result, "}")
		if end == -1 {
			break
		}
		paramName := result[start+1 : end]
		result = result[:start] + ":" + paramName + result[end+1:]
	}
	return result
}

func countRoutes(paths map[string]openAPIPathItem) int {
	count := 0
	for _, item := range paths {
		for range item {
			count++
		}
	}
	return count
}
