package main

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"

	"github.com/vyuvaraj/serv/packages/Serv-lang/compiler"
)

func runTests(srvFile string, withCoverage bool, filter string) bool {
	return runTestsWithWriter(srvFile, withCoverage, filter, os.Stdout, os.Stderr)
}

func runTestsWithWriter(srvFile string, withCoverage bool, filter string, stdoutWriter io.Writer, stderrWriter io.Writer) bool {
	absPath, program, err := parseProject(srvFile)
	if err != nil {
		fmt.Fprintf(stderrWriter, "Parse error: %v\n", err)
		return false
	}

	cg := compiler.NewCodegen(program)
	goCode, err := cg.Generate()
	if err != nil {
		fmt.Fprintf(stderrWriter, "Codegen error: %v\n", err)
		return false
	}

	if !cg.HasTests() {
		fmt.Fprintln(stdoutWriter, "No tests found in", srvFile)
		return true
	}

	buildDir := buildDirFor(absPath)
	if err := os.MkdirAll(buildDir, 0755); err != nil {
		fmt.Fprintf(stderrWriter, "Failed to create build dir: %v\n", err)
		return false
	}

	// Clean stale Go files from previous builds to prevent conflicts
	if files, err := os.ReadDir(buildDir); err == nil {
		for _, f := range files {
			if !f.IsDir() && strings.HasSuffix(f.Name(), ".go") {
				_ = os.Remove(filepath.Join(buildDir, f.Name()))
			}
		}
	}
	_ = os.Remove(filepath.Join(buildDir, "coverage.out"))

	// Write service.go: all generated declarations (functions, init blocks, etc.)
	serviceCode := goCode + "\n" + cg.GenerateHelpers()
	if err := os.WriteFile(filepath.Join(buildDir, "service.go"), []byte(serviceCode), 0644); err != nil {
		fmt.Fprintf(stderrWriter, "Failed to write service.go: %v\n", err)
		return false
	}

	// Write a minimal main.go stub (go test needs a package main with a main func)
	mainStub := "// Code generated by Serv compiler. DO NOT EDIT.\npackage main\n\nfunc main() {}\n"
	if err := os.WriteFile(filepath.Join(buildDir, "main.go"), []byte(mainStub), 0644); err != nil {
		fmt.Fprintf(stderrWriter, "Failed to write main.go: %v\n", err)
		return false
	}

	// Write serv_test.go
	testCode := cg.GenerateTests()
	testFile := filepath.Join(buildDir, "serv_test.go")
	if err := os.WriteFile(testFile, []byte(testCode), 0644); err != nil {
		fmt.Fprintf(stderrWriter, "Failed to write test file: %v\n", err)
		return false
	}

	// Ensure the build directory has a go.mod that can find serv/runtime
	goModChanged, err := ensureBuildGoMod(buildDir)
	if err != nil {
		fmt.Fprintf(stderrWriter, "Failed to setup build module: %v\n", err)
		return false
	}
	if goModChanged {
		if err := runGoModTidy(buildDir); err != nil {
			fmt.Fprintf(stderrWriter, "Failed to tidy build module: %v\n", err)
			return false
		}
	}

	fmt.Fprintf(stdoutWriter, "Running tests from %s...\n", srvFile)
	goPath, err := resolveGoPath()
	if err != nil {
		fmt.Fprintf(stderrWriter, "Cannot find Go compiler: %v\n", err)
		return false
	}

	// Build go test command with appropriate flags
	testArgs := []string{"test", "-v"}
	if withCoverage {
		coverFile := filepath.Join(buildDir, "coverage.out")
		testArgs = append(testArgs, "-coverprofile="+coverFile)
	}
	if filter != "" {
		testArgs = append(testArgs, "-run", filter)
	}
	testArgs = append(testArgs, "./...")

	cmd := exec.Command(goPath, testArgs...)
	cmd.Dir = buildDir
	cmd.Env = filterEnv(os.Environ(), "GOWORK")
	cmd.Env = append(cmd.Env, "GOWORK=off")
	if os.Getenv("SERV_ENV") == "" {
		cmd.Env = append(cmd.Env, "SERV_ENV=test")
	}
	if os.Getenv("TESTING") == "" {
		cmd.Env = append(cmd.Env, "TESTING=true")
	}
	stdoutPipe, err := cmd.StdoutPipe()
	if err != nil {
		fmt.Fprintf(stderrWriter, "Failed to create stdout pipe: %v\n", err)
		return false
	}

	stderrPipe, err := cmd.StderrPipe()
	if err != nil {
		fmt.Fprintf(stderrWriter, "Failed to create stderr pipe: %v\n", err)
		return false
	}

	if err := cmd.Start(); err != nil {
		fmt.Fprintf(stderrWriter, "Failed to start tests: %v\n", err)
		return false
	}

	rewriter := NewStackTraceRewriter(srvFile)
	var wg sync.WaitGroup
	wg.Add(2)
	go func() {
		rewriter.Rewrite(stdoutPipe, stdoutWriter)
		wg.Done()
	}()
	go func() {
		rewriter.Rewrite(stderrPipe, stderrWriter)
		wg.Done()
	}()

	testErr := cmd.Wait()
	wg.Wait()

	if testErr != nil {
		// Self-healing: if tests failed (possibly due to go.mod tidy requirement), run go mod tidy and retry once
		if tidyErr := runGoModTidy(buildDir); tidyErr == nil {
			retryCmd := exec.Command(goPath, testArgs...)
			retryCmd.Dir = buildDir
			retryCmd.Env = filterEnv(os.Environ(), "GOWORK")
			retryCmd.Env = append(retryCmd.Env, "GOWORK=off")
			if os.Getenv("SERV_ENV") == "" {
				retryCmd.Env = append(retryCmd.Env, "SERV_ENV=test")
			}
			if os.Getenv("TESTING") == "" {
				retryCmd.Env = append(retryCmd.Env, "TESTING=true")
			}
			
			retryStdoutPipe, outErr := retryCmd.StdoutPipe()
			retryStderrPipe, sErr := retryCmd.StderrPipe()
			if outErr == nil && sErr == nil {
				if startErr := retryCmd.Start(); startErr == nil {
					var retryWg sync.WaitGroup
					retryWg.Add(2)
					go func() {
						rewriter.Rewrite(retryStdoutPipe, stdoutWriter)
						retryWg.Done()
					}()
					go func() {
						rewriter.Rewrite(retryStderrPipe, stderrWriter)
						retryWg.Done()
					}()
					testErr = retryCmd.Wait()
					retryWg.Wait()
				}
			}
		}
	}


	// Show coverage summary if requested
	if withCoverage {
		coverFile := filepath.Join(buildDir, "coverage.out")
		if _, statErr := os.Stat(coverFile); statErr == nil {
			fmt.Fprintln(stdoutWriter)
			fmt.Fprintln(stdoutWriter, "--- Coverage ---")
			coverCmd := exec.Command(goPath, "tool", "cover", "-func="+coverFile)
			coverCmd.Dir = buildDir
			var coverOut bytes.Buffer
			coverCmd.Stdout = &coverOut
			coverCmd.Stderr = stderrWriter
			if err := coverCmd.Run(); err == nil {
				// Extract just the total line
				lines := strings.Split(coverOut.String(), "\n")
				for _, line := range lines {
					if strings.Contains(line, "total:") {
						fmt.Fprintln(stdoutWriter, strings.TrimSpace(line))
					}
				}
			}
			fmt.Fprintf(stdoutWriter, "Coverage profile: %s\n", coverFile)
		}
	}

	if testErr != nil {
		fmt.Fprintf(stderrWriter, "Tests failed: %v\n", testErr)
		if data, err := os.ReadFile(testFile); err == nil {
			fmt.Fprintln(stderrWriter, "--- Generated serv_test.go ---")
			lines := strings.Split(string(data), "\n")
			for idx, line := range lines {
				fmt.Fprintf(stderrWriter, "%d: %s\n", idx+1, line)
			}
		}
		return false
	}
	return true
}
