package compiler

import (
	"bytes"
	"fmt"
	"strings"
)

type ClientGenerator struct {
	Structs []*StructDecl
	Routes  []*RouteStmt
}

func NewClientGenerator(prog *Program) *ClientGenerator {
	g := &ClientGenerator{
		Structs: make([]*StructDecl, 0),
		Routes:  make([]*RouteStmt, 0),
	}

	var collect func(statements []Statement)
	collect = func(statements []Statement) {
		for _, stmt := range statements {
			switch s := stmt.(type) {
			case *StructDecl:
				g.Structs = append(g.Structs, s)
			case *RouteStmt:
				g.Routes = append(g.Routes, s)
			case *ExportStmt:
				switch inner := s.Inner.(type) {
				case *StructDecl:
					g.Structs = append(g.Structs, inner)
				case *RouteStmt:
					g.Routes = append(g.Routes, inner)
				}
			}
		}
	}
	collect(prog.Statements)
	return g
}

// Helper to generate method name from HTTP Method and Route Path
// e.g. "GET", "/api/tasks/:id" -> "getApiTasksById"
func (g *ClientGenerator) deriveMethodName(method, path string) string {
	parts := strings.Split(path, "/")
	var nameParts []string
	nameParts = append(nameParts, strings.ToLower(method))

	for _, part := range parts {
		if part == "" {
			continue
		}
		if strings.HasPrefix(part, ":") {
			paramName := strings.TrimPrefix(part, ":")
			nameParts = append(nameParts, "By"+strings.Title(paramName))
		} else {
			cleanPart := ""
			for _, char := range part {
				if (char >= 'a' && char <= 'z') || (char >= 'A' && char <= 'Z') || (char >= '0' && char <= '9') {
					cleanPart += string(char)
				}
			}
			if cleanPart != "" {
				nameParts = append(nameParts, strings.Title(cleanPart))
			}
		}
	}

	res := nameParts[0]
	for i := 1; i < len(nameParts); i++ {
		res += nameParts[i]
	}
	return res
}

// Extract path parameters from route path
func (g *ClientGenerator) getPathParams(path string) []string {
	var params []string
	parts := strings.Split(path, "/")
	for _, part := range parts {
		if strings.HasPrefix(part, ":") {
			params = append(params, strings.TrimPrefix(part, ":"))
		}
	}
	return params
}

// ---------------- TypeScript Generator ----------------

func (g *ClientGenerator) GenerateTypeScript() (string, error) {
	var buf bytes.Buffer

	buf.WriteString("/* Autogenerated Serv Client SDK for TypeScript */\n\n")

	// Generate interfaces
	for _, s := range g.Structs {
		buf.WriteString(fmt.Sprintf("export interface %s {\n", s.Name))
		for _, f := range s.Fields {
			tsType := mapTypeToTS(f.Type)
			buf.WriteString(fmt.Sprintf("  %s: %s;\n", f.Name, tsType))
		}
		buf.WriteString("}\n\n")
	}

	// Generate validation request interfaces
	for _, route := range g.Routes {
		methodLower := strings.ToLower(route.Method)
		if methodLower == "post" || methodLower == "put" || methodLower == "patch" {
			rules, keys := parseValidationMap(route.Body)
			if len(rules) > 0 {
				methodName := g.deriveMethodName(route.Method, route.Path)
				reqTypeName := strings.Title(methodName) + "Request"
				buf.WriteString(fmt.Sprintf("export interface %s {\n", reqTypeName))
				for _, k := range keys {
					ruleVal := rules[k]
					tsType := "string"
					if strings.Contains(ruleVal, "int") || strings.Contains(ruleVal, "float") {
						tsType = "number"
					} else if strings.Contains(ruleVal, "bool") {
						tsType = "boolean"
					}
					isOptional := !strings.Contains(ruleVal, "required")
					optStr := ""
					if isOptional {
						optStr = "?"
					}
					buf.WriteString(fmt.Sprintf("  %s%s: %s;\n", k, optStr, tsType))
				}
				buf.WriteString("}\n\n")
			}
		}
	}

	// Generate Client class
	buf.WriteString(`export class Client {
  private baseUrl: string;
  private token: string;

  constructor(baseUrl: string = "http://localhost:8080", token: string = "") {
    this.baseUrl = baseUrl.replace(/\/$/, "");
    this.token = token;
  }

  private async request(method: string, path: string, body?: any): Promise<any> {
    const headers: Record<string, string> = {
      "Content-Type": "application/json",
    };
    if (this.token) {
      headers["Authorization"] = "Bearer " + this.token;
    }
    const response = await fetch(this.baseUrl + path, {
      method,
      headers,
      body: body ? JSON.stringify(body) : undefined,
    });
    if (!response.ok) {
      throw new Error("HTTP error! status: " + response.status);
    }
    return response.json();
  }
`)

	for _, route := range g.Routes {
		methodName := g.deriveMethodName(route.Method, route.Path)
		params := g.getPathParams(route.Path)

		var methodArgs []string
		for _, p := range params {
			methodArgs = append(methodArgs, p+": string")
		}

		hasBody := strings.ToLower(route.Method) == "post" || strings.ToLower(route.Method) == "put" || strings.ToLower(route.Method) == "patch"
		if hasBody {
			rules, _ := parseValidationMap(route.Body)
			if len(rules) > 0 {
				reqTypeName := strings.Title(methodName) + "Request"
				methodArgs = append(methodArgs, "body: "+reqTypeName)
			} else {
				methodArgs = append(methodArgs, "body: any")
			}
		}

		argsStr := strings.Join(methodArgs, ", ")

		// Build path string replacement using simple string concatenation
		tsPathCode := fmt.Sprintf("%q", route.Path)
		for _, p := range params {
			tsPathCode = strings.ReplaceAll(tsPathCode, ":"+p, "\"+"+p+"+\"")
		}
		tsPathCode = strings.ReplaceAll(tsPathCode, "+\"\"", "")
		tsPathCode = strings.ReplaceAll(tsPathCode, "\"\"+", "")

		buf.WriteString(fmt.Sprintf("\n  async %s(%s): Promise<any> {\n", methodName, argsStr))
		if hasBody {
			buf.WriteString(fmt.Sprintf("    return this.request(%q, %s, body);\n", route.Method, tsPathCode))
		} else {
			buf.WriteString(fmt.Sprintf("    return this.request(%q, %s);\n", route.Method, tsPathCode))
		}
		buf.WriteString("  }\n")
	}

	buf.WriteString("}\n")
	return buf.String(), nil
}

func mapTypeToTS(typ string) string {
	isSlice := strings.HasPrefix(typ, "[]")
	if isSlice {
		elemType := strings.TrimPrefix(typ, "[]")
		return mapTypeToTS(elemType) + "[]"
	}
	cleanType := strings.TrimSuffix(typ, "?")
	switch cleanType {
	case "string":
		return "string"
	case "int", "integer", "float", "float64", "double", "number":
		return "number"
	case "bool", "boolean":
		return "boolean"
	case "any", "object":
		return "any"
	default:
		return cleanType
	}
}

// ---------------- Python Generator ----------------

func (g *ClientGenerator) GeneratePython() (string, error) {
	var buf bytes.Buffer

	buf.WriteString("# Autogenerated Serv Client SDK for Python\n\n")
	buf.WriteString("from dataclasses import dataclass\n")
	buf.WriteString("from typing import List, Dict, Any, Optional\n")
	buf.WriteString("import urllib.request\n")
	buf.WriteString("import urllib.error\n")
	buf.WriteString("import json\n\n")

	// Generate dataclasses
	for _, s := range g.Structs {
		buf.WriteString("@dataclass\n")
		buf.WriteString(fmt.Sprintf("class %s:\n", s.Name))
		if len(s.Fields) == 0 {
			buf.WriteString("    pass\n\n")
			continue
		}
		for _, f := range s.Fields {
			pyType := mapTypeToPython(f.Type)
			buf.WriteString(fmt.Sprintf("    %s: %s\n", f.Name, pyType))
		}
		buf.WriteString("\n")
	}

	// Generate validation request dataclasses
	for _, route := range g.Routes {
		methodLower := strings.ToLower(route.Method)
		if methodLower == "post" || methodLower == "put" || methodLower == "patch" {
			rules, keys := parseValidationMap(route.Body)
			if len(rules) > 0 {
				methodName := g.deriveMethodName(route.Method, route.Path)
				reqTypeName := strings.Title(methodName) + "Request"
				buf.WriteString("@dataclass\n")
				buf.WriteString(fmt.Sprintf("class %s:\n", reqTypeName))
				for _, k := range keys {
					ruleVal := rules[k]
					pyType := "str"
					if strings.Contains(ruleVal, "int") {
						pyType = "int"
					} else if strings.Contains(ruleVal, "float") {
						pyType = "float"
					} else if strings.Contains(ruleVal, "bool") {
						pyType = "bool"
					}
					isOptional := !strings.Contains(ruleVal, "required")
					if isOptional {
						pyType = fmt.Sprintf("Optional[%s] = None", pyType)
					}
					buf.WriteString(fmt.Sprintf("    %s: %s\n", k, pyType))
				}
				buf.WriteString("\n")
			}
		}
	}

	// Generate Client class
	buf.WriteString(`class Client:
    def __init__(self, base_url: str = "http://localhost:8080", token: str = ""):
        self.base_url = base_url.rstrip("/")
        self.token = token

    def _request(self, method: str, path: str, body: Any = None) -> Any:
        url = f"{self.base_url}{path}"
        headers = {
            "Content-Type": "application/json"
        }
        if self.token:
            headers["Authorization"] = f"Bearer {self.token}"

        data = json.dumps(body).encode("utf-8") if body is not None else None
        req = urllib.request.Request(url, data=data, headers=headers, method=method)

        try:
            with urllib.request.urlopen(req) as response:
                return json.loads(response.read().decode("utf-8"))
        except urllib.error.HTTPError as e:
            raise Exception(f"HTTP Error: {e.code} - {e.read().decode('utf-8')}")
        except Exception as e:
            raise Exception(f"Request failed: {e}")
`)

	for _, route := range g.Routes {
		methodName := g.deriveMethodName(route.Method, route.Path)
		// snake_case python method names
		methodName = camelToSnake(methodName)
		params := g.getPathParams(route.Path)

		var methodArgs []string
		methodArgs = append(methodArgs, "self")
		for _, p := range params {
			methodArgs = append(methodArgs, p+": str")
		}

		hasBody := strings.ToLower(route.Method) == "post" || strings.ToLower(route.Method) == "put" || strings.ToLower(route.Method) == "patch"
		if hasBody {
			rules, _ := parseValidationMap(route.Body)
			if len(rules) > 0 {
				rawMethodName := g.deriveMethodName(route.Method, route.Path)
				reqTypeName := strings.Title(rawMethodName) + "Request"
				methodArgs = append(methodArgs, "body: "+reqTypeName)
			} else {
				methodArgs = append(methodArgs, "body: Any")
			}
		}

		argsStr := strings.Join(methodArgs, ", ")

		// Build path string replacement
		pyPath := route.Path
		for _, p := range params {
			pyPath = strings.ReplaceAll(pyPath, ":"+p, "{"+p+"}")
		}

		buf.WriteString(fmt.Sprintf("\n    def %s(%s) -> Any:\n", methodName, argsStr))
		if hasBody {
			buf.WriteString(fmt.Sprintf("        return self._request(%q, f%q, body)\n", route.Method, pyPath))
		} else {
			buf.WriteString(fmt.Sprintf("        return self._request(%q, f%q)\n", route.Method, pyPath))
		}
	}

	return buf.String(), nil
}

func mapTypeToPython(typ string) string {
	isSlice := strings.HasPrefix(typ, "[]")
	if isSlice {
		elemType := strings.TrimPrefix(typ, "[]")
		return fmt.Sprintf("List[%s]", mapTypeToPython(elemType))
	}
	cleanType := strings.TrimSuffix(typ, "?")
	switch cleanType {
	case "string":
		return "str"
	case "int", "integer":
		return "int"
	case "float", "float64", "double":
		return "float"
	case "bool", "boolean":
		return "bool"
	case "any", "object":
		return "Any"
	default:
		return cleanType
	}
}

func camelToSnake(s string) string {
	var res []rune
	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				res = append(res, '_')
			}
			res = append(res, r+32)
		} else {
			res = append(res, r)
		}
	}
	return string(res)
}

// ---------------- Go Generator ----------------

func (g *ClientGenerator) GenerateGo() (string, error) {
	var buf bytes.Buffer

	buf.WriteString("/* Autogenerated Serv Client SDK for Go */\n\n")
	buf.WriteString("package client\n\n")
	buf.WriteString("import (\n")
	buf.WriteString("	\"bytes\"\n")
	buf.WriteString("	\"encoding/json\"\n")
	buf.WriteString("	\"fmt\"\n")
	buf.WriteString("	\"net/http\"\n")
	buf.WriteString("	\"strings\"\n")
	buf.WriteString("	\"time\"\n")
	buf.WriteString(")\n\n")

	// Generate structs
	for _, s := range g.Structs {
		buf.WriteString(fmt.Sprintf("type %s struct {\n", s.Name))
		for _, f := range s.Fields {
			goType := mapTypeToGo(f.Type)
			jsonTag := strings.ToLower(f.Name)
			buf.WriteString(fmt.Sprintf("	%s %s `json:%q`\n", strings.Title(f.Name), goType, jsonTag))
		}
		buf.WriteString("}\n\n")
	}

	// Generate validation request structs
	for _, route := range g.Routes {
		methodLower := strings.ToLower(route.Method)
		if methodLower == "post" || methodLower == "put" || methodLower == "patch" {
			rules, keys := parseValidationMap(route.Body)
			if len(rules) > 0 {
				methodName := g.deriveMethodName(route.Method, route.Path)
				reqTypeName := strings.Title(methodName) + "Request"
				buf.WriteString(fmt.Sprintf("type %s struct {\n", reqTypeName))
				for _, k := range keys {
					ruleVal := rules[k]
					goType := "string"
					if strings.Contains(ruleVal, "int") {
						goType = "int"
					} else if strings.Contains(ruleVal, "float") {
						goType = "float64"
					} else if strings.Contains(ruleVal, "bool") {
						goType = "bool"
					}
					isOptional := !strings.Contains(ruleVal, "required")
					tagOpt := ""
					if isOptional {
						tagOpt = ",omitempty"
						if goType == "int" || goType == "float64" || goType == "bool" {
							goType = "*" + goType
						}
					}
					buf.WriteString(fmt.Sprintf("	%s %s `json:%q`\n", strings.Title(k), goType, strings.ToLower(k)+tagOpt))
				}
				buf.WriteString("}\n\n")
			}
		}
	}

	// Generate Client struct
	buf.WriteString(`type Client struct {
	BaseURL    string
	Token      string
	HTTPClient *http.Client
}

func NewClient(baseURL string, token string) *Client {
	return &Client{
		BaseURL:    strings.TrimSuffix(baseURL, "/"),
		Token:      token,
		HTTPClient: &http.Client{Timeout: 10 * time.Second},
	}
}

func (c *Client) request(method, path string, body interface{}) (map[string]interface{}, error) {
	url := c.BaseURL + path
	var reqBody []byte
	var err error

	if body != nil {
		reqBody, err = json.Marshal(body)
		if err != nil {
			return nil, err
		}
	}

	req, err := http.NewRequest(method, url, bytes.NewBuffer(reqBody))
	if err != nil {
		return nil, err
	}

	req.Header.Set("Content-Type", "application/json")
	if c.Token != "" {
		req.Header.Set("Authorization", "Bearer "+c.Token)
	}

	resp, err := c.HTTPClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return nil, fmt.Errorf("HTTP error: %s", resp.Status)
	}

	var result map[string]interface{}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, err
	}

	return result, nil
}
`)

	for _, route := range g.Routes {
		methodName := g.deriveMethodName(route.Method, route.Path)
		methodName = strings.Title(methodName)
		params := g.getPathParams(route.Path)

		var methodArgs []string
		for _, p := range params {
			methodArgs = append(methodArgs, p+" string")
		}

		hasBody := strings.ToLower(route.Method) == "post" || strings.ToLower(route.Method) == "put" || strings.ToLower(route.Method) == "patch"
		if hasBody {
			rules, _ := parseValidationMap(route.Body)
			if len(rules) > 0 {
				rawMethodName := g.deriveMethodName(route.Method, route.Path)
				reqTypeName := strings.Title(rawMethodName) + "Request"
				methodArgs = append(methodArgs, "body "+reqTypeName)
			} else {
				methodArgs = append(methodArgs, "body interface{}")
			}
		}

		argsStr := strings.Join(methodArgs, ", ")

		// Build path string replacement
		goPathCode := fmt.Sprintf("%q", route.Path)
		for _, p := range params {
			goPathCode = strings.ReplaceAll(goPathCode, ":"+p, "\"+"+p+"+\"")
		}
		// Clean up redundant empty string appends if path starts/ends with params
		goPathCode = strings.ReplaceAll(goPathCode, "+\"\"", "")
		goPathCode = strings.ReplaceAll(goPathCode, "\"\"+", "")

		buf.WriteString(fmt.Sprintf("\nfunc (c *Client) %s(%s) (map[string]interface{}, error) {\n", methodName, argsStr))
		if hasBody {
			buf.WriteString(fmt.Sprintf("	return c.request(%q, %s, body)\n", route.Method, goPathCode))
		} else {
			buf.WriteString(fmt.Sprintf("	return c.request(%q, %s, nil)\n", route.Method, goPathCode))
		}
		buf.WriteString("}\n")
	}

	return buf.String(), nil
}

func mapTypeToGo(typ string) string {
	isSlice := strings.HasPrefix(typ, "[]")
	if isSlice {
		elemType := strings.TrimPrefix(typ, "[]")
		return "[]" + mapTypeToGo(elemType)
	}
	cleanType := strings.TrimSuffix(typ, "?")
	switch cleanType {
	case "string":
		return "string"
	case "int", "integer":
		return "int"
	case "float", "float64", "double":
		return "float64"
	case "bool", "boolean":
		return "bool"
	case "any", "object":
		return "interface{}"
	default:
		return cleanType
	}
}
