package compiler

import (
	"bytes"
	"fmt"
	"path/filepath"
	"strings"
)

type Codegen struct {
	program      *Program
	imports      map[string]bool
	declaredVars map[string]bool
	inFunction   bool
	goExterns    map[string]string // fnName -> pkgPath
	testFuncs    []string          // collected test functions
}

func NewCodegen(program *Program) *Codegen {
	return &Codegen{
		program:      program,
		imports:      make(map[string]bool),
		declaredVars: make(map[string]bool),
		goExterns:    make(map[string]string),
	}
}

func (c *Codegen) Generate() (string, error) {
	var body bytes.Buffer

	// Check if there are any non-test statements that would use the runtime
	hasNonTestStmts := false
	for _, stmt := range c.program.Statements {
		if _, isTest := stmt.(*TestStmt); !isTest {
			hasNonTestStmts = true
			break
		}
	}

	// Only add runtime/time imports when there are actual service statements
	if hasNonTestStmts {
		c.imports[`"serv/runtime"`] = true
		c.imports[`"time"`] = true
	}

	// First pass: extract externs and imports to build the header
	for _, stmt := range c.program.Statements {
		if ext, ok := stmt.(*ExternFnStmt); ok {
			if strings.HasPrefix(ext.Source, "go:") {
				// Format: "go:importPath:FunctionName"
				parts := strings.Split(strings.TrimPrefix(ext.Source, "go:"), ":")
				if len(parts) >= 2 {
					pkgPath := parts[0]
					// Add package import
					c.imports[`"`+pkgPath+`"`] = true
					// Extract package name from path
					pkgName := filepath.Base(pkgPath)
					c.goExterns[ext.Name] = pkgName + "." + parts[1]
				}
			}
		}
	}

	// Generate body
	for _, stmt := range c.program.Statements {
		gen, err := c.genStatement(stmt)
		if err != nil {
			return "", err
		}
		body.WriteString(gen)
	}

	// Build final output with imports
	var out bytes.Buffer
	out.WriteString("// Code generated by Serv compiler. DO NOT EDIT.\n")
	out.WriteString("package main\n\n")

	if len(c.imports) > 0 {
		out.WriteString("import (\n")
		for imp := range c.imports {
			out.WriteString("\t" + imp + "\n")
		}
		out.WriteString(")\n\n")
	}

	// Blank identifier guards to prevent "imported and not used" errors
	if c.imports[`"time"`] {
		out.WriteString("var _ = time.Second // ensure time is used\n\n")
	}
	if c.imports[`"fmt"`] {
		out.WriteString("var _ = fmt.Sprintf // ensure fmt is used\n\n")
	}
	if c.imports[`"serv/runtime"`] {
		out.WriteString("var _ = runtime.Noop // ensure runtime is used\n\n")
	}


	out.WriteString(body.String())

	return out.String(), nil
}


func (c *Codegen) genStatement(stmt Statement) (string, error) {
	switch s := stmt.(type) {
	case *ImportStmt:
		// Local imports are handled at parser stage by merging ASTs, so nothing to output here
		return "", nil

	case *ExternFnStmt:
		// Generate the Go wrapper function
		var out bytes.Buffer
		out.WriteString(fmt.Sprintf("func %s(", s.Name))
		var params []string
		for _, p := range s.Params {
			params = append(params, p+" interface{}")
		}
		out.WriteString(strings.Join(params, ", "))
		out.WriteString(") interface{} {\n")

		if strings.HasPrefix(s.Source, "go:") {
			goCall, ok := c.goExterns[s.Name]
			if !ok {
				return "", fmt.Errorf("missing go call mapping for extern fn: %s", s.Name)
			}
			var callArgs []string
			for _, p := range s.Params {
				// Go packages might expect string or other types; we pass as is or cast if needed.
				// In general, we pass the interface{} values.
				callArgs = append(callArgs, p)
			}
			out.WriteString(fmt.Sprintf("\treturn %s(%s)\n", goCall, strings.Join(callArgs, ", ")))
		} else if strings.HasPrefix(s.Source, "python:") {
			// python:./scripts/analyzer.py:analyze
			parts := strings.Split(strings.TrimPrefix(s.Source, "python:"), ":")
			if len(parts) >= 2 {
				scriptPath := parts[0]
				funcName := parts[1]
				var callArgs []string
				for _, p := range s.Params {
					callArgs = append(callArgs, p)
				}
				argsStr := ""
				if len(callArgs) > 0 {
					argsStr = ", " + strings.Join(callArgs, ", ")
				}
				out.WriteString(fmt.Sprintf("\treturn runtime.CallPython(%q, %q%s)\n", scriptPath, funcName, argsStr))
			} else {
				return "", fmt.Errorf("invalid python extern source: %s", s.Source)
			}
		}

		out.WriteString("}\n\n")
		return out.String(), nil

	case *BrokerStmt:
		val, err := c.genExpression(s.Value)
		if err != nil {
			return "", err
		}
		// In main() or global init, but Serv puts setup in main.
		// Let's output these setups into standard setup blocks that will go into main() later
		return fmt.Sprintf("func init() {\n\truntime.InitBroker(fmt.Sprint(%s))\n}\n\n", val), nil

	case *ServerStmt:
		val, err := c.genExpression(s.Value)
		if err != nil {
			return "", err
		}
		c.imports[`"fmt"`] = true
		return fmt.Sprintf("func init() {\n\truntime.InitServer(fmt.Sprint(%s))\n}\n\n", val), nil

	case *DatabaseStmt:
		val, err := c.genExpression(s.Value)
		if err != nil {
			return "", err
		}
		c.imports[`"fmt"`] = true
		return fmt.Sprintf("func init() {\n\truntime.InitDB(fmt.Sprint(%s))\n}\n\n", val), nil

	case *CacheStmt:
		val, err := c.genExpression(s.Value)
		if err != nil {
			return "", err
		}
		c.imports[`"fmt"`] = true
		return fmt.Sprintf("func init() {\n\truntime.InitCache(fmt.Sprint(%s))\n}\n\n", val), nil

	case *MatchStmt:
		valStr, err := c.genExpression(s.Value)
		if err != nil {
			return "", err
		}
		var out bytes.Buffer
		out.WriteString(fmt.Sprintf("switch %s {\n", valStr))
		for _, cs := range s.Cases {
			if cs.Value != nil {
				caseVal, err := c.genExpression(cs.Value)
				if err != nil {
					return "", err
				}
				bodyStr, err := c.genBlockStatement(cs.Body)
				if err != nil {
					return "", err
				}
				out.WriteString(fmt.Sprintf("case %s: %s\n", caseVal, bodyStr))
			} else {
				bodyStr, err := c.genBlockStatement(cs.Body)
				if err != nil {
					return "", err
				}
				out.WriteString(fmt.Sprintf("default: %s\n", bodyStr))
			}
		}
		out.WriteString("}\n")
		return out.String(), nil

	case *RouteStmt:
		bodyStr, err := c.genBlockStatement(s.Body)
		if err != nil {
			return "", err
		}
		// Wrap returning map or response correctly
		return fmt.Sprintf("func init() {\n\truntime.AddRoute(%q, %q, func(%s runtime.Request) interface{} %s)\n}\n\n", s.Method, s.Path, s.Param, bodyStr), nil

	case *EveryStmt:
		interval, err := c.genExpression(s.Interval)
		if err != nil {
			return "", err
		}
		bodyStr, err := c.genBlockStatement(s.Body)
		if err != nil {
			return "", err
		}
		c.imports[`"fmt"`] = true
		return fmt.Sprintf("func init() {\n\t// Scheduled interval job\n\tgo func() {\n\t\ttime.Sleep(100 * time.Millisecond) // brief sleep to let server initialize\n\t\truntime.Every(fmt.Sprint(%s), func() %s)\n\t}()\n}\n\n", interval, bodyStr), nil

	case *CronStmt:
		cronVal, err := c.genExpression(s.Cron)
		if err != nil {
			return "", err
		}
		bodyStr, err := c.genBlockStatement(s.Body)
		if err != nil {
			return "", err
		}
		c.imports[`"fmt"`] = true
		return fmt.Sprintf("func init() {\n\t// Scheduled cron job\n\tgo func() {\n\t\ttime.Sleep(100 * time.Millisecond)\n\t\truntime.Cron(fmt.Sprint(%s), func() %s)\n\t}()\n}\n\n", cronVal, bodyStr), nil

	case *SubscribeStmt:
		topic, err := c.genExpression(s.Topic)
		if err != nil {
			return "", err
		}
		bodyStr, err := c.genBlockStatement(s.Body)
		if err != nil {
			return "", err
		}
		c.imports[`"fmt"`] = true
		return fmt.Sprintf("func init() {\n\truntime.Subscribe(fmt.Sprint(%s), func(%s string) %s)\n}\n\n", topic, s.Param, bodyStr), nil

	case *PublishStmt:
		topic, err := c.genExpression(s.Topic)
		if err != nil {
			return "", err
		}
		val, err := c.genExpression(s.Value)
		if err != nil {
			return "", err
		}
		c.imports[`"fmt"`] = true
		return fmt.Sprintf("runtime.Publish(fmt.Sprint(%s), %s)\n", topic, val), nil

	case *SpawnStmt:
		call, err := c.genExpression(s.Call)
		if err != nil {
			return "", err
		}
		if s.Limit != nil {
			limStr, err := c.genExpression(s.Limit)
			if err != nil {
				return "", err
			}
			semID := fmt.Sprintf("spawn_%d_%d", s.Token.Line, s.Token.Col)
			c.imports[`"fmt"`] = true
			c.imports[`"strconv"`] = true
			return fmt.Sprintf("runtime.AcquireSemaphore(%q, func() int {\n\t\t\tval, _ := strconv.Atoi(fmt.Sprint(%s))\n\t\t\tif val <= 0 { return 1 }\n\t\t\treturn val\n\t\t}())\ngo func() {\n\t\tdefer runtime.ReleaseSemaphore(%q)\n\t\t%s\n\t}()\n", semID, limStr, semID, call), nil
		}
		return fmt.Sprintf("go func() {\n\t\t%s\n\t}()\n", call), nil

	case *TestStmt:
		// Collect test function bodies — emitted separately via GenerateTests()
		funcName := "Test_" + sanitizeTestName(s.Name)
		bodyStr, err := c.genBlockStatement(s.Body)
		if err != nil {
			return "", err
		}
		c.testFuncs = append(c.testFuncs, fmt.Sprintf("func %s(t *testing.T) %s\n", funcName, bodyStr))
		return "", nil

	case *LetStmt:
		val, err := c.genExpression(s.Value)
		if err != nil {
			return "", err
		}
		// If already declared in current block scope, assign normal; else declare with var
		// Since we transpiled function scope simply, we check if it is declared.
		if c.declaredVars[s.Name] {
			return fmt.Sprintf("%s = %s\n_ = %s\n", s.Name, val, s.Name), nil
		}
		c.declaredVars[s.Name] = true
		if c.inFunction {
			return fmt.Sprintf("var %s interface{} = %s\n_ = %s\n", s.Name, val, s.Name), nil
		}
		// Global let
		return fmt.Sprintf("var %s interface{} = %s\n", s.Name, val), nil

	case *ReturnStmt:
		val, err := c.genExpression(s.Value)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("return %s\n", val), nil

	case *FnDecl:
		c.inFunction = true
		// Clear local variables for this function scope
		oldDeclared := c.declaredVars
		c.declaredVars = make(map[string]bool)
		for _, p := range s.Params {
			c.declaredVars[p] = true
		}

		bodyStr, err := c.genBlockStatement(s.Body)
		if err != nil {
			return "", err
		}

		c.declaredVars = oldDeclared
		c.inFunction = false

		var params []string
		for _, p := range s.Params {
			params = append(params, p+" interface{}")
		}

		// Ensure we have a return statement if none is at the end
		hasReturn := false
		if len(s.Body.Statements) > 0 {
			lastStmt := s.Body.Statements[len(s.Body.Statements)-1]
			if _, ok := lastStmt.(*ReturnStmt); ok {
				hasReturn = true
			}
		}

		if !hasReturn {
			if strings.HasSuffix(bodyStr, "}") {
				bodyStr = bodyStr[:len(bodyStr)-1] + "\treturn nil\n}"
			}
		}

		return fmt.Sprintf("func %s(%s) interface{} %s\n\n", s.Name, strings.Join(params, ", "), bodyStr), nil

	case *TryCatchStmt:
		oldDeclared := c.declaredVars
		c.declaredVars = make(map[string]bool)
		for k, v := range oldDeclared {
			c.declaredVars[k] = v
		}
		c.declaredVars[s.Param] = true

		tryBodyStr, err := c.genBlockStatement(s.TryBody)
		if err != nil {
			return "", err
		}

		catchBodyStr, err := c.genBlockStatement(s.CatchBody)
		if err != nil {
			return "", err
		}

		c.declaredVars = oldDeclared

		return fmt.Sprintf("func() {\n\tdefer func() {\n\t\tif r := recover(); r != nil {\n\t\t\tvar %s interface{} = r\n\t\t\t_ = %s\n\t\t\t%s\n\t\t}\n\t}()\n\t%s\n}()\n", s.Param, s.Param, catchBodyStr, tryBodyStr), nil

	case *ExprStmt:
		expr, err := c.genExpression(s.Value)
		if err != nil {
			return "", err
		}
		if !c.inFunction {
			return fmt.Sprintf("func init() {\n\t%s\n}\n\n", expr), nil
		}
		return expr + "\n", nil

	default:
		return "", fmt.Errorf("unknown statement type: %T", stmt)
	}
}

func (c *Codegen) genBlockStatement(block *BlockStmt) (string, error) {
	oldInFunc := c.inFunction
	c.inFunction = true
	defer func() { c.inFunction = oldInFunc }()

	var out bytes.Buffer
	out.WriteString("{\n")
	for _, s := range block.Statements {
		gen, err := c.genStatement(s)
		if err != nil {
			return "", err
		}
		// Indent lines
		lines := strings.Split(gen, "\n")
		for _, line := range lines {
			if strings.TrimSpace(line) != "" {
				out.WriteString("\t" + line + "\n")
			}
		}
	}
	out.WriteString("}")
	return out.String(), nil
}

func (c *Codegen) genExpression(expr Expression) (string, error) {
	switch e := expr.(type) {
	case *Identifier:
		// Map standard builtins like log.info, metric.inc, http.get
		// Wait, they are parsed as MemberExpr if they use dot notation.
		// If it's a simple identifier, output it
		return e.Value, nil

	case *StringLiteral:
		return fmt.Sprintf("%q", e.Value), nil

	case *IntegerLiteral:
		return fmt.Sprintf("%d", e.Value), nil

	case *DurationLiteral:
		return fmt.Sprintf("%q", e.Value), nil

	case *MemberExpr:
		objStr, err := c.genExpression(e.Object)
		if err != nil {
			return "", err
		}

		// Builtin conversions
		if objStr == "time" && e.Field == "now" {
			return "func() interface{} { return time.Now().Format(time.RFC3339) }", nil
		}

		if objStr == "log" {
			if e.Field == "info" {
				return "runtime.LogInfo", nil
			} else if e.Field == "warn" {
				return "runtime.LogWarn", nil
			} else if e.Field == "error" {
				return "runtime.LogError", nil
			}
		}
		if objStr == "metric" {
			if e.Field == "inc" {
				return "runtime.MetricInc", nil
			} else if e.Field == "gauge" {
				return "runtime.MetricGauge", nil
			}
		}
		if objStr == "http" {
			if e.Field == "get" {
				return "runtime.HTTPGet", nil
			} else if e.Field == "post" {
				return "runtime.HTTPPost", nil
			}
		}
		if objStr == "json" {
			if e.Field == "parse" {
				return "runtime.JSONParse", nil
			} else if e.Field == "stringify" {
				return "runtime.JSONStringify", nil
			}
		}
		if objStr == "db" {
			if e.Field == "query" {
				return "runtime.DBQuery", nil
			}
		}
		if objStr == "cache" {
			if e.Field == "set" {
				return "runtime.CacheSet", nil
			} else if e.Field == "get" {
				return "runtime.CacheGet", nil
			}
		}

		// Direct Go member access e.g. req.body
		// We'll support .Body and .Status fields (or map them casing)
		field := e.Field
		if field == "body" {
			field = "Body"
		} else if field == "status" {
			field = "Status"
		}
		// Since objects might be interface{}, we have to perform type assertion or dynamic access.
		// For our Request / HTTPResponse structs, they are returned statically.
		// So we cast: if e.Object is req, we do req.Body.
		// Let's produce a safe Go dynamic field access or standard access:
		return fmt.Sprintf("func() interface{} {\n\t\t\t// Safe member access\n\t\t\tval := interface{}(%s)\n\t\t\tswitch v := val.(type) {\n\t\t\tcase runtime.Request:\n\t\t\t\tif %q == \"Body\" { return v.Body }\n\t\t\t\tif %q == \"Method\" { return v.Method }\n\t\t\t\tif %q == \"Path\" { return v.Path }\n\t\t\tcase runtime.HTTPResponse:\n\t\t\t\tif %q == \"Body\" { return v.Body }\n\t\t\t\tif %q == \"Status\" { return v.Status }\n\t\t\tcase map[string]interface{}:\n\t\t\t\treturn v[%q]\n\t\t\t}\n\t\t\treturn nil\n\t\t}()", objStr, field, field, field, field, field, e.Field), nil

	case *MemberAssignExpr:
		objStr, err := c.genExpression(e.Object)
		if err != nil {
			return "", err
		}
		valStr, err := c.genExpression(e.Value)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("func() interface{} {\n\t\t\t// Safe member assignment\n\t\t\tif m, ok := interface{}(%s).(map[string]interface{}); ok {\n\t\t\t\tm[%q] = %s\n\t\t\t}\n\t\t\treturn nil\n\t\t}()", objStr, e.Field, valStr), nil

	case *CallExpr:
		funcStr, err := c.genExpression(e.Function)
		if err != nil {
			return "", err
		}

		var args []string
		for _, arg := range e.Arguments {
			argStr, err := c.genExpression(arg)
			if err != nil {
				return "", err
			}
			args = append(args, argStr)
		}

		// Builtin conversions for Env and Config
		if funcStr == "env" {
			return fmt.Sprintf("runtime.Env(%s)", strings.Join(args, ", ")), nil
		}
		if funcStr == "config" {
			return fmt.Sprintf("runtime.Config(%s)", strings.Join(args, ", ")), nil
		}

		// Special case: time.now()
		if funcStr == "time.now" {
			return "time.Now().Format(time.RFC3339)", nil
		}

		return fmt.Sprintf("%s(%s)", funcStr, strings.Join(args, ", ")), nil

	case *FStringLiteral:
		return c.genFString(e.Value)

	case *MapLiteral:
		var pairs []string
		for k, v := range e.Pairs {
			vStr, err := c.genExpression(v)
			if err != nil {
				return "", err
			}
			pairs = append(pairs, fmt.Sprintf("%q: %s", k, vStr))
		}
		return fmt.Sprintf("map[string]interface{}{\n\t\t%s,\n\t}", strings.Join(pairs, ",\n\t\t")), nil

	case *InfixExpr:
		leftStr, err := c.genExpression(e.Left)
		if err != nil {
			return "", err
		}
		rightStr, err := c.genExpression(e.Right)
		if err != nil {
			return "", err
		}
		// Since operands are interface{} in Serv, we add a utility to add/concatenate/compare if needed.
		// Comparison operators return bool; arithmetic operators return numeric/string.
		switch e.Operator {
		case "==":
			c.imports[`"fmt"`] = true
			return fmt.Sprintf("(func() interface{} { return fmt.Sprintf(\"%%v\", %s) == fmt.Sprintf(\"%%v\", %s) }())", leftStr, rightStr), nil
		case "!=":
			c.imports[`"fmt"`] = true
			return fmt.Sprintf("(func() interface{} { return fmt.Sprintf(\"%%v\", %s) != fmt.Sprintf(\"%%v\", %s) }())", leftStr, rightStr), nil
		case "<", ">", "<=", ">=":
			return fmt.Sprintf("(func() interface{} {\n\t\t\tl, r := interface{}(%s), interface{}(%s)\n\t\t\tswitch lv := l.(type) {\n\t\t\tcase int:\n\t\t\t\tif rv, ok := r.(int); ok { return lv %s rv }\n\t\t\tcase int64:\n\t\t\t\tif rv, ok := r.(int64); ok { return lv %s rv }\n\t\t\tcase float64:\n\t\t\t\tif rv, ok := r.(float64); ok { return lv %s rv }\n\t\t\t}\n\t\t\treturn false\n\t\t}())", leftStr, rightStr, e.Operator, e.Operator, e.Operator), nil
		default:
			// Arithmetic operators
			return fmt.Sprintf("(func() interface{} {\n\t\t\tswitch l := interface{}(%s).(type) {\n\t\t\tcase int:\n\t\t\t\tif r, ok := interface{}(%s).(int); ok {\n\t\t\t\t\treturn l %s r\n\t\t\t\t}\n\t\t\tcase int64:\n\t\t\t\tif r, ok := interface{}(%s).(int64); ok {\n\t\t\t\t\treturn l %s r\n\t\t\t\t}\n\t\t\tcase float64:\n\t\t\t\tif r, ok := interface{}(%s).(float64); ok {\n\t\t\t\t\treturn l %s r\n\t\t\t\t}\n\t\t\tcase string:\n\t\t\t\tif r, ok := interface{}(%s).(string); ok {\n\t\t\t\t\treturn l %s r\n\t\t\t\t}\n\t\t\t}\n\t\t\treturn nil\n\t\t}())", leftStr, rightStr, e.Operator, rightStr, e.Operator, rightStr, e.Operator, rightStr, e.Operator), nil
		}



	case *AssignExpr:
		valStr, err := c.genExpression(e.Value)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("%s = %s", e.Name, valStr), nil

	case *AssertExpr:
		condStr, err := c.genExpression(e.Cond)
		if err != nil {
			return "", err
		}
		// Generate: if !(cond) { t.Fatalf("assertion failed: %v", cond) }
		return fmt.Sprintf("func() {\n\t\tif v := %s; v == nil || v == false {\n\t\t\tt.Fatalf(\"assertion failed: %%v\", v)\n\t\t}\n\t}()", condStr), nil

	default:
		return "", fmt.Errorf("unknown expression type: %T", expr)
	}
}

// GenerateMainFunc creates the entrypoint function main() which runs runtime.StartServer()
func (c *Codegen) GenerateMainFunc() string {
	return `func main() {
	runtime.StartServer()
}
`
}

// HasTests reports whether any test blocks were found during code generation.
func (c *Codegen) HasTests() bool {
	return len(c.testFuncs) > 0
}

// GenerateTests emits a Go _test.go file containing all collected test functions.
// The caller is responsible for writing this to a file named e.g. "serv_test.go".

func (c *Codegen) GenerateTests() string {
	var out bytes.Buffer
	out.WriteString("// Code generated by Serv compiler. DO NOT EDIT.\n")
	out.WriteString("package main\n\n")
	out.WriteString("import (\n")
	out.WriteString("\t\"fmt\"\n")
	out.WriteString("\t\"testing\"\n")
	out.WriteString(")\n\n")
	out.WriteString("var _ = fmt.Sprintf // keep fmt import\n\n")
	for _, fn := range c.testFuncs {
		out.WriteString(fn)
		out.WriteString("\n")
	}
	return out.String()
}

// capitalizeFirst uppercases the first rune of s.
func capitalizeFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// sanitizeTestName converts a human-readable test name (may contain spaces, dashes, etc.)
// into a valid Go identifier by title-casing each word and stripping non-alphanumeric chars.
func sanitizeTestName(name string) string {
	words := strings.FieldsFunc(name, func(r rune) bool {
		return r == ' ' || r == '-' || r == '_' || r == '.' || r == '/'
	})
	var out strings.Builder
	for _, w := range words {
		if w == "" {
			continue
		}
		out.WriteString(strings.ToUpper(w[:1]) + w[1:])
	}
	result := out.String()
	if result == "" {
		return "Unnamed"
	}
	return result
}


func (c *Codegen) genFString(str string) (string, error) {
	c.imports[`"fmt"`] = true
	var formatParts []string
	var args []string

	runes := []rune(str)
	i := 0
	n := len(runes)
	currentText := ""

	for i < n {
		if runes[i] == '{' {
			if currentText != "" {
				formatParts = append(formatParts, currentText)
				currentText = ""
			}
			i++
			exprText := ""
			for i < n && runes[i] != '}' {
				exprText += string(runes[i])
				i++
			}
			if i >= n {
				return "", fmt.Errorf("unterminated brace in f-string")
			}
			i++ // skip '}'
			formatParts = append(formatParts, "%v")
			args = append(args, exprText)
		} else {
			currentText += string(runes[i])
			i++
		}
	}
	if currentText != "" {
		formatParts = append(formatParts, currentText)
	}

	formatStr := strings.Join(formatParts, "")
	if len(args) == 0 {
		return fmt.Sprintf("%q", formatStr), nil
	}
	return fmt.Sprintf("fmt.Sprintf(%q, %s)", formatStr, strings.Join(args, ", ")), nil
}
