package compiler

import "bytes"

// HasTests reports whether any test blocks were found during code generation.
func (c *Codegen) HasTests() bool {
	return len(c.testFuncs) > 0
}

// GenerateTests emits a Go _test.go file containing all collected test functions.
// The caller is responsible for writing this to a file named e.g. "serv_test.go".
func (c *Codegen) GenerateTests() string {
	var out bytes.Buffer
	out.WriteString("// Code generated by Serv compiler. DO NOT EDIT.\n")
	out.WriteString("package main\n\n")
	out.WriteString("import (\n")
	out.WriteString("\t\"fmt\"\n")
	out.WriteString("\t\"testing\"\n")
	for imp := range c.imports {
		if imp != `"testing"` && imp != `"fmt"` {
			out.WriteString("\t")
			out.WriteString(imp)
			out.WriteString("\n")
		}
	}
	out.WriteString(")\n\n")
	out.WriteString("var _ = fmt.Sprintf // keep fmt import\n")
	if c.imports[`"time"`] {
		out.WriteString("var _ = time.Second\n")
	}
	if c.imports[`"serv/runtime"`] {
		out.WriteString("var _ = runtime.Noop\n")
	}
	if c.imports[`"strconv"`] {
		out.WriteString("var _ = strconv.Atoi\n")
	}
	if c.imports[`"regexp"`] {
		out.WriteString("var _ = regexp.MustCompile\n")
	}
	out.WriteString("\n")
	for _, fn := range c.testFuncs {
		out.WriteString(fn)
		out.WriteString("\n")
	}
	return out.String()
}
