package compiler

import (
	"bytes"
	"fmt"
	"path/filepath"
	"strings"
)

type Codegen struct {
	program             *Program
	imports             map[string]bool
	declaredVars        map[string]bool
	varTypes            map[string]string // varName -> type
	inFunction          bool
	inConcurrentContext bool
	goExterns           map[string]string // fnName -> pkgPath
	testFuncs           []string          // collected test functions
	regexDecls          []string          // collected compiled regex variables
	structTypes         map[string]bool   // known struct type names
	funcReturnTypes     map[string]string // fnName -> return type
}

func NewCodegen(program *Program) *Codegen {
	return &Codegen{
		program:             program,
		imports:             make(map[string]bool),
		declaredVars:        make(map[string]bool),
		varTypes:     make(map[string]string),
		goExterns:    make(map[string]string),
		regexDecls:   []string{},
		structTypes:  make(map[string]bool),
		funcReturnTypes: make(map[string]string),
	}
}

func (c *Codegen) Generate() (string, error) {
	var body bytes.Buffer

	// Check if there are any non-test statements that would use the runtime
	hasNonTestStmts := false
	for _, stmt := range c.program.Statements {
		if _, isTest := stmt.(*TestStmt); !isTest {
			hasNonTestStmts = true
			break
		}
	}

	// Only add runtime/time imports when there are actual service statements
	if hasNonTestStmts {
		c.imports[`"serv/runtime"`] = true
		c.imports[`"time"`] = true
	}

	// Pre-pass: collect struct type names and function return types
	for _, stmt := range c.program.Statements {
		switch s := stmt.(type) {
		case *StructDecl:
			c.structTypes[s.Name] = true
		case *FnDecl:
			if s.ReturnType != "" {
				c.funcReturnTypes[s.Name] = s.ReturnType
			}
		case *ExportStmt:
			switch inner := s.Inner.(type) {
			case *StructDecl:
				c.structTypes[inner.Name] = true
			case *FnDecl:
				if inner.ReturnType != "" {
					c.funcReturnTypes[inner.Name] = inner.ReturnType
				}
			}
		}
	}

	// First pass: extract externs and imports to build the header
	for _, stmt := range c.program.Statements {
		if ext, ok := stmt.(*ExternFnStmt); ok {
			if strings.HasPrefix(ext.Source, "go:") {
				// Format: "go:importPath:FunctionName"
				parts := strings.Split(strings.TrimPrefix(ext.Source, "go:"), ":")
				if len(parts) >= 2 {
					pkgPath := parts[0]
					// Add package import
					c.imports[`"`+pkgPath+`"`] = true
					// Extract package name from path
					pkgName := filepath.Base(pkgPath)
					c.goExterns[ext.Name] = pkgName + "." + parts[1]
				}
			}
		}
	}

	// Generate body
	for _, stmt := range c.program.Statements {
		// Emit source line reference for traceability
		if tok := stmtToken(stmt); tok.Line > 0 {
			body.WriteString(fmt.Sprintf("// .srv line %d\n", tok.Line))
		}
		gen, err := c.genStatement(stmt)
		if err != nil {
			return "", err
		}
		body.WriteString(gen)
	}

	// Build final output with imports
	var out bytes.Buffer
	out.WriteString("// Code generated by Serv compiler. DO NOT EDIT.\n")
	out.WriteString("package main\n\n")

	if len(c.imports) > 0 {
		out.WriteString("import (\n")
		for imp := range c.imports {
			out.WriteString("\t" + imp + "\n")
		}
		out.WriteString(")\n\n")
	}

	// Blank identifier guards to prevent "imported and not used" errors
	if c.imports[`"time"`] {
		out.WriteString("var _ = time.Second // ensure time is used\n\n")
	}
	if c.imports[`"fmt"`] {
		out.WriteString("var _ = fmt.Sprintf // ensure fmt is used\n\n")
	}
	if c.imports[`"serv/runtime"`] {
		out.WriteString("var _ = runtime.Noop // ensure runtime is used\n\n")
	}
	if c.imports[`"strconv"`] {
		out.WriteString("var _ = strconv.Atoi // ensure strconv is used\n\n")
	}
	if c.imports[`"regexp"`] {
		out.WriteString("var _ = regexp.MustCompile // ensure regexp is used\n\n")
	}

	// Pre-compiled regex variables
	if len(c.regexDecls) > 0 {
		for _, rDecl := range c.regexDecls {
			out.WriteString(rDecl + "\n")
		}
		out.WriteString("\n")
	}

	out.WriteString(body.String())

	return out.String(), nil
}


func (c *Codegen) genStatement(stmt Statement) (string, error) {
	switch s := stmt.(type) {
	case *ImportStmt:
		// Local imports are handled at parser stage by merging ASTs, so nothing to output here
		return "", nil

	case *ExportStmt:
		// Export is a visibility marker; generate the inner statement normally
		return c.genStatement(s.Inner)

	case *ExternFnStmt:
		// Generate the Go wrapper function
		var out bytes.Buffer
		out.WriteString(fmt.Sprintf("func %s(", s.Name))
		var params []string
		for _, p := range s.Params {
			params = append(params, p+" interface{}")
		}
		out.WriteString(strings.Join(params, ", "))
		out.WriteString(") interface{} {\n")

		if strings.HasPrefix(s.Source, "go:") {
			goCall, ok := c.goExterns[s.Name]
			if !ok {
				return "", fmt.Errorf("missing go call mapping for extern fn: %s", s.Name)
			}
			var callArgs []string
			for _, p := range s.Params {
				// Go packages might expect string or other types; we pass as is or cast if needed.
				// In general, we pass the interface{} values.
				callArgs = append(callArgs, p)
			}
			out.WriteString(fmt.Sprintf("\treturn %s(%s)\n", goCall, strings.Join(callArgs, ", ")))
		} else if strings.HasPrefix(s.Source, "python:") {
			// python:./scripts/analyzer.py:analyze
			parts := strings.Split(strings.TrimPrefix(s.Source, "python:"), ":")
			if len(parts) >= 2 {
				scriptPath := parts[0]
				funcName := parts[1]
				if absPath, err := filepath.Abs(scriptPath); err == nil {
					scriptPath = filepath.ToSlash(absPath)
				}
				var callArgs []string
				for _, p := range s.Params {
					callArgs = append(callArgs, p)
				}
				argsStr := ""
				if len(callArgs) > 0 {
					argsStr = ", " + strings.Join(callArgs, ", ")
				}
				out.WriteString(fmt.Sprintf("\treturn runtime.CallPython(%q, %q%s)\n", scriptPath, funcName, argsStr))
			} else {
				return "", fmt.Errorf("invalid python extern source: %s", s.Source)
			}
		}

		out.WriteString("}\n\n")
		return out.String(), nil

	case *EnumStmt:
		var rOut bytes.Buffer
		rOut.WriteString("const (\n")
		for _, m := range s.Members {
			c.varTypes[m] = "string"
			rOut.WriteString(fmt.Sprintf("\t%s = %q\n", m, m))
		}
		rOut.WriteString(")\n\n")
		return rOut.String(), nil

	case *IfStmt:
		condStr, err := c.genExpression(s.Condition)
		if err != nil {
			return "", err
		}
		bodyStr, err := c.genBlockStatement(s.Body)
		if err != nil {
			return "", err
		}
		// Wrap condition in a truthiness check for interface{} values
		condType := c.getExpressionType(s.Condition)
		var condCode string
		if condType == "bool" {
			condCode = condStr
		} else {
			condCode = fmt.Sprintf("isTruthy(%s)", condStr)
		}
		if s.ElseBody != nil {
			elseStr, err := c.genBlockStatement(s.ElseBody)
			if err != nil {
				return "", err
			}
			return fmt.Sprintf("if %s %s else %s\n", condCode, bodyStr, elseStr), nil
		}
		return fmt.Sprintf("if %s %s\n", condCode, bodyStr), nil

	case *ForStmt:
		if s.IsRange {
			iterStr, err := c.genExpression(s.Iterable)
			if err != nil {
				return "", err
			}
			c.declaredVars[s.Variable] = true
			bodyStr, err := c.genBlockStatement(s.Body)
			if err != nil {
				return "", err
			}
			return fmt.Sprintf("for _, %s := range toSlice(%s) %s\n", s.Variable, iterStr, bodyStr), nil
		}
		// Condition-based loop
		condStr, err := c.genExpression(s.Iterable)
		if err != nil {
			return "", err
		}
		bodyStr, err := c.genBlockStatement(s.Body)
		if err != nil {
			return "", err
		}
		condType := c.getExpressionType(s.Iterable)
		var condCode string
		if condType == "bool" {
			condCode = condStr
		} else {
			condCode = fmt.Sprintf("isTruthy(%s)", condStr)
		}
		return fmt.Sprintf("for %s %s\n", condCode, bodyStr), nil

	case *StructDecl:
		var out bytes.Buffer
		out.WriteString(fmt.Sprintf("type %s struct {\n", s.Name))
		for _, f := range s.Fields {
			goType := toGoType(f.Type)
			if goType == "interface{}" {
				// Check if it's a known struct type
				goType = f.Type
			}
			out.WriteString(fmt.Sprintf("\t%s %s\n", capitalizeFirst(f.Name), goType))
		}
		out.WriteString("}\n\n")
		// Register struct type for later use
		c.varTypes[s.Name] = s.Name
		return out.String(), nil

	case *MethodDecl:
		c.inFunction = true
		oldDeclared := c.declaredVars
		oldVarTypes := c.varTypes
		c.declaredVars = make(map[string]bool)
		c.varTypes = make(map[string]string)
		for k, v := range oldVarTypes {
			c.varTypes[k] = v
		}
		c.declaredVars["self"] = true
		c.varTypes["self"] = s.TypeName

		var params []string
		for i, p := range s.Params {
			c.declaredVars[p] = true
			pt := "interface{}"
			if i < len(s.ParamTypes) && s.ParamTypes[i] != "" {
				pt = toGoType(s.ParamTypes[i])
				c.varTypes[p] = pt
			}
			params = append(params, p+" "+pt)
		}

		bodyStr, err := c.genBlockStatement(s.Body)
		if err != nil {
			return "", err
		}

		c.declaredVars = oldDeclared
		c.varTypes = oldVarTypes
		c.inFunction = false

		retType := "interface{}"
		if s.ReturnType != "" {
			retType = toGoType(s.ReturnType)
			if retType == "interface{}" {
				retType = s.ReturnType // might be a struct type
			}
		}

		// Generate as Go method with pointer receiver
		return fmt.Sprintf("func (self *%s) %s(%s) %s %s\n\n", s.TypeName, capitalizeFirst(s.Name), strings.Join(params, ", "), retType, bodyStr), nil

	case *InterfaceDecl:
		var out bytes.Buffer
		out.WriteString(fmt.Sprintf("type %s interface {\n", s.Name))
		for _, m := range s.Methods {
			var params []string
			for i, p := range m.Params {
				pt := "interface{}"
				if i < len(m.ParamTypes) && m.ParamTypes[i] != "" {
					pt = toGoType(m.ParamTypes[i])
				}
				params = append(params, p+" "+pt)
			}
			retType := "interface{}"
			if m.ReturnType != "" {
				retType = toGoType(m.ReturnType)
				if retType == "interface{}" {
					retType = m.ReturnType
				}
			}
			out.WriteString(fmt.Sprintf("\t%s(%s) %s\n", capitalizeFirst(m.Name), strings.Join(params, ", "), retType))
		}
		out.WriteString("}\n\n")
		return out.String(), nil

	case *BrokerStmt:
		val, err := c.genExpression(s.Value)
		if err != nil {
			return "", err
		}
		// In main() or global init, but Serv puts setup in main.
		// Let's output these setups into standard setup blocks that will go into main() later
		return fmt.Sprintf("func init() {\n\truntime.InitBroker(fmt.Sprint(%s))\n}\n\n", val), nil

	case *ServerStmt:
		val, err := c.genExpression(s.Value)
		if err != nil {
			return "", err
		}
		c.imports[`"fmt"`] = true
		return fmt.Sprintf("func init() {\n\truntime.InitServer(fmt.Sprint(%s))\n}\n\n", val), nil

	case *DatabaseStmt:
		val, err := c.genExpression(s.Value)
		if err != nil {
			return "", err
		}
		c.imports[`"fmt"`] = true
		return fmt.Sprintf("func init() {\n\truntime.InitDB(fmt.Sprint(%s))\n}\n\n", val), nil

	case *CacheStmt:
		val, err := c.genExpression(s.Value)
		if err != nil {
			return "", err
		}
		c.imports[`"fmt"`] = true
		return fmt.Sprintf("func init() {\n\truntime.InitCache(fmt.Sprint(%s))\n}\n\n", val), nil

	case *MatchStmt:
		valStr, err := c.genExpression(s.Value)
		if err != nil {
			return "", err
		}
		var out bytes.Buffer
		out.WriteString(fmt.Sprintf("switch %s {\n", valStr))
		for _, cs := range s.Cases {
			if cs.Value != nil {
				caseVal, err := c.genExpression(cs.Value)
				if err != nil {
					return "", err
				}
				bodyStr, err := c.genBlockStatement(cs.Body)
				if err != nil {
					return "", err
				}
				out.WriteString(fmt.Sprintf("case %s: %s\n", caseVal, bodyStr))
			} else {
				bodyStr, err := c.genBlockStatement(cs.Body)
				if err != nil {
					return "", err
				}
				out.WriteString(fmt.Sprintf("default: %s\n", bodyStr))
			}
		}
		out.WriteString("}\n")
		return out.String(), nil

	case *RouteStmt:
		bodyStr, err := c.genBlockStatement(s.Body)
		if err != nil {
			return "", err
		}
		// Wrap returning map or response correctly
		return fmt.Sprintf("func init() {\n\truntime.AddRoute(%q, %q, %d, %q, func(%s runtime.Request) interface{} %s)\n}\n\n", s.Method, s.Path, s.LimitRate, s.LimitPeriod, s.Param, bodyStr), nil

	case *ToolStmt:
		bodyStr, err := c.genBlockStatement(s.Body)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("func init() {\n\truntime.AddMCPTool(%q, %q, func(%s interface{}) interface{} %s)\n}\n\n", s.Name, s.Description, s.Param, bodyStr), nil

	case *MigrationStmt:
		bodyStr, err := c.genBlockStatement(s.Body)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("func init() {\n\truntime.RegisterMigration(%q, func() %s)\n}\n\n", s.Name, bodyStr), nil

	case *EveryStmt:
		interval, err := c.genExpression(s.Interval)
		if err != nil {
			return "", err
		}
		bodyStr, err := c.genBlockStatement(s.Body)
		if err != nil {
			return "", err
		}
		c.imports[`"fmt"`] = true
		return fmt.Sprintf("func init() {\n\t// Scheduled interval job\n\tgo func() {\n\t\ttime.Sleep(100 * time.Millisecond) // brief sleep to let server initialize\n\t\truntime.Every(fmt.Sprint(%s), func() %s)\n\t}()\n}\n\n", interval, bodyStr), nil

	case *CronStmt:
		cronVal, err := c.genExpression(s.Cron)
		if err != nil {
			return "", err
		}
		bodyStr, err := c.genBlockStatement(s.Body)
		if err != nil {
			return "", err
		}
		c.imports[`"fmt"`] = true
		return fmt.Sprintf("func init() {\n\t// Scheduled cron job\n\tgo func() {\n\t\ttime.Sleep(100 * time.Millisecond)\n\t\truntime.Cron(fmt.Sprint(%s), func() %s)\n\t}()\n}\n\n", cronVal, bodyStr), nil

	case *SubscribeStmt:
		topic, err := c.genExpression(s.Topic)
		if err != nil {
			return "", err
		}
		bodyStr, err := c.genBlockStatement(s.Body)
		if err != nil {
			return "", err
		}
		c.imports[`"fmt"`] = true
		return fmt.Sprintf("func init() {\n\truntime.Subscribe(fmt.Sprint(%s), func(%s string) %s)\n}\n\n", topic, s.Param, bodyStr), nil

	case *PublishStmt:
		topic, err := c.genExpression(s.Topic)
		if err != nil {
			return "", err
		}
		val, err := c.genExpression(s.Value)
		if err != nil {
			return "", err
		}
		c.imports[`"fmt"`] = true
		return fmt.Sprintf("runtime.Publish(fmt.Sprint(%s), %s)\n", topic, val), nil

	case *SpawnStmt:
		call, err := c.genExpression(s.Call)
		if err != nil {
			return "", err
		}
		if s.Limit != nil {
			limStr, err := c.genExpression(s.Limit)
			if err != nil {
				return "", err
			}
			semID := fmt.Sprintf("spawn_%d_%d", s.Token.Line, s.Token.Col)
			c.imports[`"fmt"`] = true
			c.imports[`"strconv"`] = true
			return fmt.Sprintf("runtime.AcquireSemaphore(%q, func() int {\n\t\t\tval, _ := strconv.Atoi(fmt.Sprint(%s))\n\t\t\tif val <= 0 { return 1 }\n\t\t\treturn val\n\t\t}())\ngo func() {\n\t\tdefer runtime.ReleaseSemaphore(%q)\n\t\tdefer func() {\n\t\t\tif r := recover(); r != nil {\n\t\t\t\truntime.LogError(\"Recovered in spawned task: \", r)\n\t\t\t}\n\t\t}()\n\t\t%s\n\t}()\n", semID, limStr, semID, call), nil
		}
		return fmt.Sprintf("go func() {\n\t\tdefer func() {\n\t\t\tif r := recover(); r != nil {\n\t\t\t\truntime.LogError(\"Recovered in spawned task: \", r)\n\t\t\t}\n\t\t}()\n\t\t%s\n\t}()\n", call), nil

	case *TestStmt:
		c.inFunction = true
		oldConcurrent := c.inConcurrentContext
		c.inConcurrentContext = hasConcurrency(s.Body)

		// Collect test function bodies — emitted separately via GenerateTests()
		funcName := "Test_" + sanitizeTestName(s.Name)
		bodyStr, err := c.genBlockStatement(s.Body)
		if err != nil {
			return "", err
		}
		c.inFunction = false
		c.inConcurrentContext = oldConcurrent
		c.testFuncs = append(c.testFuncs, fmt.Sprintf("func %s(t *testing.T) %s\n", funcName, bodyStr))
		return "", nil

	case *LetStmt:
		val, err := c.genExpression(s.Value)
		if err != nil {
			return "", err
		}

		// Multi-return: let val, err = expr
		if len(s.Names) > 1 {
			for _, name := range s.Names {
				c.declaredVars[name] = true
			}
			c.imports[`"fmt"`] = true
			// Generate a safe call that catches panics and returns (value, error)
			return fmt.Sprintf("%s, %s := safeCall(func() interface{} { return %s })\n_ = %s\n_ = %s\n",
				s.Names[0], s.Names[1], val, s.Names[0], s.Names[1]), nil
		}

		// If already declared in current block scope, assign normal; else declare with var
		if c.declaredVars[s.Name] {
			return fmt.Sprintf("%s = %s\n_ = %s\n", s.Name, val, s.Name), nil
		}
		c.declaredVars[s.Name] = true
		goType := "interface{}"
		if s.Type != "" {
			goType = toGoType(s.Type)
			if goType == "interface{}" {
				// Could be a struct type name
				goType = "*" + s.Type
			}
			c.varTypes[s.Name] = s.Type
		} else if structLit, ok := s.Value.(*StructLiteral); ok {
			// Infer struct type from literal
			goType = "*" + structLit.TypeName
			c.varTypes[s.Name] = structLit.TypeName
		} else if callExpr, ok := s.Value.(*CallExpr); ok {
			// Infer type from function return type
			if ident, ok := callExpr.Function.(*Identifier); ok {
				if retType, exists := c.funcReturnTypes[ident.Value]; exists && c.structTypes[retType] {
					goType = "*" + retType
					c.varTypes[s.Name] = retType
				}
			}
		} else {
			inferred := c.getExpressionType(s.Value)
			if inferred != "interface{}" {
				goType = inferred
				c.varTypes[s.Name] = goType
			}
		}
		if c.inFunction {
			return fmt.Sprintf("var %s %s = %s\n_ = %s\n", s.Name, goType, val, s.Name), nil
		}
		// Global let
		return fmt.Sprintf("var %s %s = %s\n", s.Name, goType, val), nil

	case *ReturnStmt:
		val, err := c.genExpression(s.Value)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("return %s\n", val), nil

	case *FnDecl:
		c.inFunction = true
		oldConcurrent := c.inConcurrentContext
		c.inConcurrentContext = hasConcurrency(s.Body)

		// Clear local variables for this function scope
		oldDeclared := c.declaredVars
		oldVarTypes := c.varTypes
		c.declaredVars = make(map[string]bool)
		c.varTypes = make(map[string]string)
		for k, v := range oldVarTypes {
			c.varTypes[k] = v
		}

		var params []string
		for i, p := range s.Params {
			c.declaredVars[p] = true
			pt := "interface{}"
			if i < len(s.ParamTypes) && s.ParamTypes[i] != "" {
				pt = toGoType(s.ParamTypes[i])
				c.varTypes[p] = pt
			}
			params = append(params, p+" "+pt)
		}

		bodyStr, err := c.genBlockStatement(s.Body)
		if err != nil {
			return "", err
		}

		c.declaredVars = oldDeclared
		c.varTypes = oldVarTypes
		c.inFunction = false
		c.inConcurrentContext = oldConcurrent

		retType := "interface{}"
		if s.ReturnType != "" {
			retType = toGoType(s.ReturnType)
			if retType == "interface{}" && c.structTypes[s.ReturnType] {
				retType = "*" + s.ReturnType
			}
		}
		hasReturn := false
		if len(s.Body.Statements) > 0 {
			lastStmt := s.Body.Statements[len(s.Body.Statements)-1]
			if _, ok := lastStmt.(*ReturnStmt); ok {
				hasReturn = true
			}
		}

		if !hasReturn {
			if strings.HasSuffix(bodyStr, "}") {
				bodyStr = bodyStr[:len(bodyStr)-1] + fmt.Sprintf("\treturn %s\n}", zeroValue(retType))
			}
		}

		return fmt.Sprintf("func %s(%s) %s %s\n\n", s.Name, strings.Join(params, ", "), retType, bodyStr), nil

	case *TryCatchStmt:
		oldDeclared := c.declaredVars
		c.declaredVars = make(map[string]bool)
		for k, v := range oldDeclared {
			c.declaredVars[k] = v
		}
		c.declaredVars[s.Param] = true

		tryBodyStr, err := c.genBlockStatement(s.TryBody)
		if err != nil {
			return "", err
		}

		catchBodyStr, err := c.genBlockStatement(s.CatchBody)
		if err != nil {
			return "", err
		}

		c.declaredVars = oldDeclared

		return fmt.Sprintf("func() {\n\tdefer func() {\n\t\tif r := recover(); r != nil {\n\t\t\tvar %s interface{} = r\n\t\t\t_ = %s\n\t\t\t%s\n\t\t}\n\t}()\n\t%s\n}()\n", s.Param, s.Param, catchBodyStr, tryBodyStr), nil

	case *ExprStmt:
		expr, err := c.genExpression(s.Value)
		if err != nil {
			return "", err
		}
		if !c.inFunction {
			return fmt.Sprintf("func init() {\n\t%s\n}\n\n", expr), nil
		}
		return expr + "\n", nil

	default:
		return "", fmt.Errorf("unknown statement type: %T", stmt)
	}
}

func (c *Codegen) genBlockStatement(block *BlockStmt) (string, error) {
	oldInFunc := c.inFunction
	c.inFunction = true
	defer func() { c.inFunction = oldInFunc }()

	var out bytes.Buffer
	out.WriteString("{\n")
	for _, s := range block.Statements {
		gen, err := c.genStatement(s)
		if err != nil {
			return "", err
		}
		// Indent lines
		lines := strings.Split(gen, "\n")
		for _, line := range lines {
			if strings.TrimSpace(line) != "" {
				out.WriteString("\t" + line + "\n")
			}
		}
	}
	out.WriteString("}")
	return out.String(), nil
}

func (c *Codegen) genExpression(expr Expression) (string, error) {
	switch e := expr.(type) {
	case *Identifier:
		// Map standard builtins like log.info, metric.inc, http.get
		// Wait, they are parsed as MemberExpr if they use dot notation.
		// If it's a simple identifier, output it
		return e.Value, nil

	case *StringLiteral:
		return fmt.Sprintf("%q", e.Value), nil

	case *IntegerLiteral:
		return fmt.Sprintf("%d", e.Value), nil

	case *FloatLiteral:
		return fmt.Sprintf("%f", e.Value), nil

	case *ArrayLiteral:
		var elements []string
		for _, el := range e.Elements {
			elStr, err := c.genExpression(el)
			if err != nil {
				return "", err
			}
			elements = append(elements, elStr)
		}
		return fmt.Sprintf("[]interface{}{%s}", strings.Join(elements, ", ")), nil

	case *DurationLiteral:
		return fmt.Sprintf("%q", e.Value), nil

	case *MemberExpr:
		objStr, err := c.genExpression(e.Object)
		if err != nil {
			return "", err
		}

		// Self field access: self.field -> self.Field (direct struct access)
		if _, isSelf := e.Object.(*SelfExpr); isSelf {
			return fmt.Sprintf("self.%s", capitalizeFirst(e.Field)), nil
		}

		// Struct instance field access: if the object is a known struct type variable
		if objType, ok := c.varTypes[objStr]; ok && objType != "interface{}" && objType != "int" && objType != "string" && objType != "float64" && objType != "bool" && objType != "[]interface{}" {
			return fmt.Sprintf("%s.%s", objStr, capitalizeFirst(e.Field)), nil
		}

		// Builtin conversions
		if objStr == "time" && e.Field == "now" {
			return "func() interface{} { return time.Now().Format(time.RFC3339) }", nil
		}

		if objStr == "log" {
			if e.Field == "info" {
				return "runtime.LogInfo", nil
			} else if e.Field == "warn" {
				return "runtime.LogWarn", nil
			} else if e.Field == "error" {
				return "runtime.LogError", nil
			}
		}
		if objStr == "metric" {
			if e.Field == "inc" {
				return "runtime.MetricInc", nil
			} else if e.Field == "gauge" {
				return "runtime.MetricGauge", nil
			}
		}
		if objStr == "http" {
			if e.Field == "get" {
				return "runtime.HTTPGet", nil
			} else if e.Field == "post" {
				return "runtime.HTTPPost", nil
			}
		}
		if objStr == "json" {
			if e.Field == "parse" {
				return "runtime.JSONParse", nil
			} else if e.Field == "stringify" {
				return "runtime.JSONStringify", nil
			}
		}
		if objStr == "db" {
			if e.Field == "query" {
				return "runtime.DBQuery", nil
			} else if e.Field == "beforeQuery" {
				return "runtime.AddBeforeQueryHook", nil
			}
		}
		if objStr == "cache" {
			if e.Field == "set" {
				return "runtime.CacheSet", nil
			} else if e.Field == "get" {
				return "runtime.CacheGet", nil
			}
		}
		if objStr == "mcp" {
			if e.Field == "call" {
				return "runtime.InvokeMCPToolForTesting", nil
			}
		}

		// Collection property access (no parentheses needed)
		if e.Field == "length" {
			return fmt.Sprintf("runtime.Length(%s)", objStr), nil
		}

		// Direct Go member access e.g. req.body
		// We'll support .Body and .Status fields (or map them casing)
		field := e.Field
		if field == "body" {
			field = "Body"
		} else if field == "status" {
			field = "Status"
		}
		// Since objects might be interface{}, we have to perform type assertion or dynamic access.
		// For our Request / HTTPResponse structs, they are returned statically.
		// So we cast: if e.Object is req, we do req.Body.
		// Let's produce a safe Go dynamic field access or standard access:
		return fmt.Sprintf("func() interface{} {\n\t\t\t// Safe member access\n\t\t\tval := interface{}(%s)\n\t\t\tswitch v := val.(type) {\n\t\t\tcase runtime.Request:\n\t\t\t\tif %q == \"Body\" { return v.Body }\n\t\t\t\tif %q == \"Method\" { return v.Method }\n\t\t\t\tif %q == \"Path\" { return v.Path }\n\t\t\tcase runtime.HTTPResponse:\n\t\t\t\tif %q == \"Body\" { return v.Body }\n\t\t\t\tif %q == \"Status\" { return v.Status }\n\t\t\tcase *runtime.SafeMap:\n\t\t\t\treturn v.Get(%q)\n\t\t\tcase map[string]interface{}:\n\t\t\t\treturn v[%q]\n\t\t\t}\n\t\t\treturn nil\n\t\t}()", objStr, field, field, field, field, field, e.Field, e.Field), nil

	case *MemberAssignExpr:
		objStr, err := c.genExpression(e.Object)
		if err != nil {
			return "", err
		}
		valStr, err := c.genExpression(e.Value)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("func() interface{} {\n\t\t\t// Safe member assignment\n\t\t\tif sm, ok := interface{}(%s).(*runtime.SafeMap); ok {\n\t\t\t\tsm.Set(%q, %s)\n\t\t\t} else if m, ok := interface{}(%s).(map[string]interface{}); ok {\n\t\t\t\tm[%q] = %s\n\t\t\t}\n\t\t\treturn nil\n\t\t}()", objStr, e.Field, valStr, objStr, e.Field, valStr), nil

	case *CallExpr:
		var funcStr string
		var isRegexpCheck bool
		var isCollectionMethod bool
		var collectionResult string
		var isStructMethodCall bool
		var structMethodResult string

		if memExpr, ok := e.Function.(*MemberExpr); ok {
			objStr, err := c.genExpression(memExpr.Object)
			if err == nil && objStr == "regexp" && memExpr.Field == "check" {
				isRegexpCheck = true
				funcStr = "regexp.check"
			}

			// Struct method calls: if the object is a known struct type, generate direct call
			if err == nil && !isRegexpCheck {
				objType := ""
				if ident, ok := memExpr.Object.(*Identifier); ok {
					if t, exists := c.varTypes[ident.Value]; exists {
						objType = t
					}
				} else if _, ok := memExpr.Object.(*SelfExpr); ok {
					if t, exists := c.varTypes["self"]; exists {
						objType = t
					}
				}
				// Check if it's a struct type (not a primitive)
				if objType != "" && objType != "interface{}" && objType != "int" && objType != "string" && objType != "float64" && objType != "bool" && objType != "[]interface{}" {
					var args []string
					for _, arg := range e.Arguments {
						argStr, err := c.genExpression(arg)
						if err != nil {
							break
						}
						args = append(args, argStr)
					}
					structMethodResult = fmt.Sprintf("%s.%s(%s)", objStr, capitalizeFirst(memExpr.Field), strings.Join(args, ", "))
					isStructMethodCall = true
				}
			}

			// Collection methods: .filter, .map, .find, .reduce, .forEach, .length, .push, .contains
			if err == nil && !isRegexpCheck {
				switch memExpr.Field {
				case "filter":
					if len(e.Arguments) == 1 {
						argStr, _ := c.genCollectionCallback(e.Arguments[0])
						collectionResult = fmt.Sprintf("runtime.Filter(%s, %s)", objStr, argStr)
						isCollectionMethod = true
					}
				case "map":
					if len(e.Arguments) == 1 {
						argStr, _ := c.genCollectionCallback(e.Arguments[0])
						collectionResult = fmt.Sprintf("runtime.Map(%s, %s)", objStr, argStr)
						isCollectionMethod = true
					}
				case "find":
					if len(e.Arguments) == 1 {
						argStr, _ := c.genCollectionCallback(e.Arguments[0])
						collectionResult = fmt.Sprintf("runtime.Find(%s, %s)", objStr, argStr)
						isCollectionMethod = true
					}
				case "reduce":
					if len(e.Arguments) == 2 {
						cbStr, _ := c.genReduceCallback(e.Arguments[0])
						initStr, _ := c.genExpression(e.Arguments[1])
						collectionResult = fmt.Sprintf("runtime.Reduce(%s, %s, %s)", objStr, cbStr, initStr)
						isCollectionMethod = true
					}
				case "forEach":
					if len(e.Arguments) == 1 {
						argStr, _ := c.genCollectionCallback(e.Arguments[0])
						collectionResult = fmt.Sprintf("runtime.ForEach(%s, %s)", objStr, argStr)
						isCollectionMethod = true
					}
				case "length":
					collectionResult = fmt.Sprintf("runtime.Length(%s)", objStr)
					isCollectionMethod = true
				case "push":
					if len(e.Arguments) == 1 {
						elemStr, _ := c.genExpression(e.Arguments[0])
						collectionResult = fmt.Sprintf("runtime.Push(%s, %s)", objStr, elemStr)
						isCollectionMethod = true
					}
				case "contains":
					if len(e.Arguments) == 1 {
						elemStr, _ := c.genExpression(e.Arguments[0])
						collectionResult = fmt.Sprintf("runtime.Contains(%s, %s)", objStr, elemStr)
						isCollectionMethod = true
					}
				}
			}
		}

		if isCollectionMethod {
			return collectionResult, nil
		}

		if isStructMethodCall {
			return structMethodResult, nil
		}

		if !isRegexpCheck {
			var err error
			funcStr, err = c.genExpression(e.Function)
			if err != nil {
				return "", err
			}
		}

		var args []string
		for _, arg := range e.Arguments {
			argStr, err := c.genExpression(arg)
			if err != nil {
				return "", err
			}
			args = append(args, argStr)
		}

		// Builtin conversions for Env and Config
		if funcStr == "env" {
			return fmt.Sprintf("runtime.Env(%s)", strings.Join(args, ", ")), nil
		}
		if funcStr == "config" {
			return fmt.Sprintf("runtime.Config(%s)", strings.Join(args, ", ")), nil
		}

		// Special case: time.now()
		if funcStr == "time.now" {
			return "time.Now().Format(time.RFC3339)", nil
		}

		if funcStr == "regexp.check" && len(e.Arguments) == 2 {
			c.imports[`"regexp"`] = true
			textVal, err := c.genExpression(e.Arguments[1])
			if err != nil {
				return "", err
			}
			c.imports[`"fmt"`] = true
			if strLit, ok := e.Arguments[0].(*StringLiteral); ok {
				varName := fmt.Sprintf("regex_%d_%d", e.Token.Line, e.Token.Col)
				decl := fmt.Sprintf("var %s = regexp.MustCompile(%q)", varName, strLit.Value)
				c.regexDecls = append(c.regexDecls, decl)
				return fmt.Sprintf("%s.MatchString(fmt.Sprint(%s))", varName, textVal), nil
			} else {
				patternVal, err := c.genExpression(e.Arguments[0])
				if err != nil {
					return "", err
				}
				return fmt.Sprintf("(func() bool { r, err := regexp.Compile(fmt.Sprint(%s)); if err != nil { return false }; return r.MatchString(fmt.Sprint(%s)) }())", patternVal, textVal), nil
			}
		}

		return fmt.Sprintf("%s(%s)", funcStr, strings.Join(args, ", ")), nil

	case *FStringLiteral:
		return c.genFString(e.Value)

	case *MapLiteral:
		var pairs []string
		for _, k := range e.KeyOrder {
			v := e.Pairs[k]
			vStr, err := c.genExpression(v)
			if err != nil {
				return "", err
			}
			pairs = append(pairs, fmt.Sprintf("%q: %s", k, vStr))
		}
		if c.inFunction && !c.inConcurrentContext {
			return fmt.Sprintf("map[string]interface{}{\n\t\t%s,\n\t}", strings.Join(pairs, ",\n\t\t")), nil
		}
		return fmt.Sprintf("runtime.NewSafeMapFromMap(map[string]interface{}{\n\t\t%s,\n\t})", strings.Join(pairs, ",\n\t\t")), nil

	case *IndexExpr:
		leftStr, err := c.genExpression(e.Left)
		if err != nil {
			return "", err
		}
		indexStr, err := c.genExpression(e.Index)
		if err != nil {
			return "", err
		}
		c.imports[`"fmt"`] = true
		c.imports[`"strconv"`] = true
		c.imports[`"serv/runtime"`] = true
		return fmt.Sprintf("func() interface{} {\n\t\t\tval := interface{}(%s)\n\t\t\tswitch v := val.(type) {\n\t\t\tcase []interface{}:\n\t\t\t\tidx, _ := strconv.Atoi(fmt.Sprint(%s))\n\t\t\t\tif idx >= 0 && idx < len(v) {\n\t\t\t\t\treturn v[idx]\n\t\t\t\t}\n\t\t\tcase *runtime.SafeMap:\n\t\t\t\treturn v.Get(fmt.Sprint(%s))\n\t\t\tcase map[string]interface{}:\n\t\t\t\treturn v[fmt.Sprint(%s)]\n\t\t\t}\n\t\t\treturn nil\n\t\t}()", leftStr, indexStr, indexStr, indexStr), nil

	case *InfixExpr:
		leftStr, err := c.genExpression(e.Left)
		if err != nil {
			return "", err
		}
		rightStr, err := c.genExpression(e.Right)
		if err != nil {
			return "", err
		}

		lt := c.getExpressionType(e.Left)
		rt := c.getExpressionType(e.Right)

		if lt == rt && (lt == "int" || lt == "float64" || lt == "string" || lt == "bool") {
			return fmt.Sprintf("(%s %s %s)", leftStr, e.Operator, rightStr), nil
		}

		// Since operands are interface{} in Serv, we add a utility to add/concatenate/compare if needed.
		// Comparison operators return bool; arithmetic operators return numeric/string.
		switch e.Operator {
		case "==":
			// Special case: comparison with nil
			if _, isNil := e.Right.(*NilLiteral); isNil {
				return fmt.Sprintf("(%s == nil)", leftStr), nil
			}
			if _, isNil := e.Left.(*NilLiteral); isNil {
				return fmt.Sprintf("(%s == nil)", rightStr), nil
			}
			c.imports[`"fmt"`] = true
			return fmt.Sprintf("(fmt.Sprintf(\"%%v\", %s) == fmt.Sprintf(\"%%v\", %s))", leftStr, rightStr), nil
		case "!=":
			// Special case: comparison with nil
			if _, isNil := e.Right.(*NilLiteral); isNil {
				return fmt.Sprintf("(%s != nil)", leftStr), nil
			}
			if _, isNil := e.Left.(*NilLiteral); isNil {
				return fmt.Sprintf("(%s != nil)", rightStr), nil
			}
			c.imports[`"fmt"`] = true
			return fmt.Sprintf("(fmt.Sprintf(\"%%v\", %s) != fmt.Sprintf(\"%%v\", %s))", leftStr, rightStr), nil
		case "<", ">", "<=", ">=":
			return fmt.Sprintf("(func() bool {\n\t\t\tl, r := interface{}(%s), interface{}(%s)\n\t\t\tswitch lv := l.(type) {\n\t\t\tcase int:\n\t\t\t\tif rv, ok := r.(int); ok { return lv %s rv }\n\t\t\tcase int64:\n\t\t\t\tif rv, ok := r.(int64); ok { return lv %s rv }\n\t\t\tcase float64:\n\t\t\t\tif rv, ok := r.(float64); ok { return lv %s rv }\n\t\t\t}\n\t\t\treturn false\n\t\t}())", leftStr, rightStr, e.Operator, e.Operator, e.Operator), nil
		default:
			// Arithmetic operators
			return fmt.Sprintf("(func() interface{} {\n\t\t\tswitch l := interface{}(%s).(type) {\n\t\t\tcase int:\n\t\t\t\tif r, ok := interface{}(%s).(int); ok {\n\t\t\t\t\treturn l %s r\n\t\t\t\t}\n\t\t\tcase int64:\n\t\t\t\tif r, ok := interface{}(%s).(int64); ok {\n\t\t\t\t\treturn l %s r\n\t\t\t\t}\n\t\t\tcase float64:\n\t\t\t\tif r, ok := interface{}(%s).(float64); ok {\n\t\t\t\t\treturn l %s r\n\t\t\t\t}\n\t\t\tcase string:\n\t\t\t\tif r, ok := interface{}(%s).(string); ok {\n\t\t\t\t\treturn l %s r\n\t\t\t\t}\n\t\t\t}\n\t\t\treturn nil\n\t\t}())", leftStr, rightStr, e.Operator, rightStr, e.Operator, rightStr, e.Operator, rightStr, e.Operator), nil
		}



	case *AssignExpr:
		valStr, err := c.genExpression(e.Value)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("%s = %s", e.Name, valStr), nil

	case *BooleanLiteral:
		if e.Value {
			return "true", nil
		}
		return "false", nil

	case *NilLiteral:
		return "nil", nil

	case *SelfExpr:
		return "self", nil

	case *StructLiteral:
		var fields []string
		for _, k := range e.KeyOrder {
			v := e.Fields[k]
			vStr, err := c.genExpression(v)
			if err != nil {
				return "", err
			}
			fields = append(fields, fmt.Sprintf("%s: %s", capitalizeFirst(k), vStr))
		}
		return fmt.Sprintf("&%s{\n\t\t%s,\n\t}", e.TypeName, strings.Join(fields, ",\n\t\t")), nil

	case *AssertExpr:
		condStr, err := c.genExpression(e.Cond)
		if err != nil {
			return "", err
		}
		// Generate: if !(cond) { t.Fatalf("assertion failed: %v", cond) }
		return fmt.Sprintf("func() {\n\t\tvar v interface{} = %s\n\t\tif v == nil || v == false {\n\t\t\tt.Fatalf(\"assertion failed: %%v\", v)\n\t\t}\n\t}()", condStr), nil

	default:
		return "", fmt.Errorf("unknown expression type: %T", expr)
	}
}

// GenerateMainFunc creates the entrypoint function main() which runs runtime.StartServer()
func (c *Codegen) GenerateMainFunc() string {
	return `func main() {
	runtime.StartServer()
}
`
}

// GenerateHelpers returns utility functions needed by generated code (if/for/multi-return support).
func (c *Codegen) GenerateHelpers() string {
	return `
// isTruthy evaluates truthiness of an interface{} value.
func isTruthy(v interface{}) bool {
	if v == nil {
		return false
	}
	switch val := v.(type) {
	case bool:
		return val
	case int:
		return val != 0
	case int64:
		return val != 0
	case float64:
		return val != 0
	case string:
		return val != ""
	default:
		return true
	}
}

// toSlice coerces an interface{} to []interface{} for range iteration.
func toSlice(v interface{}) []interface{} {
	if v == nil {
		return nil
	}
	if s, ok := v.([]interface{}); ok {
		return s
	}
	return nil
}

// multiReturn splits a value into (result, error) for multi-return assignment.
// If the value is a [2]interface{} tuple, it unpacks it.
// If the value is an error, returns (nil, error).
// Otherwise returns (value, nil).
func multiReturn(v interface{}) (interface{}, interface{}) {
	if v == nil {
		return nil, nil
	}
	if tuple, ok := v.([2]interface{}); ok {
		return tuple[0], tuple[1]
	}
	if err, ok := v.(error); ok {
		return nil, err.Error()
	}
	return v, nil
}

// safeCall executes a function and catches any panic, returning (result, error).
// Used by multi-return let statements: let val, err = expr
func safeCall(fn func() interface{}) (interface{}, interface{}) {
	var result interface{}
	var errVal interface{}
	func() {
		defer func() {
			if r := recover(); r != nil {
				errVal = fmt.Sprint(r)
			}
		}()
		result = fn()
	}()
	// If the result is already a tuple (from safe runtime functions), unpack it
	if tuple, ok := result.([2]interface{}); ok {
		return tuple[0], tuple[1]
	}
	return result, errVal
}
`
}

// HasTests reports whether any test blocks were found during code generation.
func (c *Codegen) HasTests() bool {
	return len(c.testFuncs) > 0
}

// GenerateTests emits a Go _test.go file containing all collected test functions.
// The caller is responsible for writing this to a file named e.g. "serv_test.go".

func (c *Codegen) GenerateTests() string {
	var out bytes.Buffer
	out.WriteString("// Code generated by Serv compiler. DO NOT EDIT.\n")
	out.WriteString("package main\n\n")
	out.WriteString("import (\n")
	out.WriteString("\t\"fmt\"\n")
	out.WriteString("\t\"testing\"\n")
	for imp := range c.imports {
		if imp != `"testing"` && imp != `"fmt"` {
			out.WriteString("\t" + imp + "\n")
		}
	}
	out.WriteString(")\n\n")
	out.WriteString("var _ = fmt.Sprintf // keep fmt import\n")
	if c.imports[`"time"`] {
		out.WriteString("var _ = time.Second\n")
	}
	if c.imports[`"serv/runtime"`] {
		out.WriteString("var _ = runtime.Noop\n")
	}
	if c.imports[`"strconv"`] {
		out.WriteString("var _ = strconv.Atoi\n")
	}
	if c.imports[`"regexp"`] {
		out.WriteString("var _ = regexp.MustCompile\n")
	}
	out.WriteString("\n")
	for _, fn := range c.testFuncs {
		out.WriteString(fn)
		out.WriteString("\n")
	}
	return out.String()
}

// capitalizeFirst uppercases the first rune of s.
func capitalizeFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// sanitizeTestName converts a human-readable test name (may contain spaces, dashes, etc.)
// into a valid Go identifier by title-casing each word and stripping non-alphanumeric chars.
func sanitizeTestName(name string) string {
	words := strings.FieldsFunc(name, func(r rune) bool {
		return r == ' ' || r == '-' || r == '_' || r == '.' || r == '/'
	})
	var out strings.Builder
	for _, w := range words {
		if w == "" {
			continue
		}
		out.WriteString(strings.ToUpper(w[:1]) + w[1:])
	}
	result := out.String()
	if result == "" {
		return "Unnamed"
	}
	return result
}


// genCollectionCallback generates a Go function literal for collection method callbacks.
// Handles identifiers (function references) and inline fn expressions.
func (c *Codegen) genCollectionCallback(expr Expression) (string, error) {
	// If it's a simple identifier (function name), wrap it
	if ident, ok := expr.(*Identifier); ok {
		return fmt.Sprintf("func(item interface{}) interface{} { return %s(item) }", ident.Value), nil
	}
	// If it's a call expression that looks like fn(x) { body }, it would have been parsed differently.
	// For now, generate the expression and wrap it as a callable
	exprStr, err := c.genExpression(expr)
	if err != nil {
		return "", err
	}
	return fmt.Sprintf("func(item interface{}) interface{} { return %s(item) }", exprStr), nil
}

// genReduceCallback generates a Go function literal for reduce callbacks (2 params).
func (c *Codegen) genReduceCallback(expr Expression) (string, error) {
	if ident, ok := expr.(*Identifier); ok {
		return fmt.Sprintf("func(acc interface{}, item interface{}) interface{} { return %s(acc, item) }", ident.Value), nil
	}
	exprStr, err := c.genExpression(expr)
	if err != nil {
		return "", err
	}
	return fmt.Sprintf("func(acc interface{}, item interface{}) interface{} { return %s(acc, item) }", exprStr), nil
}

func (c *Codegen) genFString(str string) (string, error) {
	var formatParts []string
	var args []string

	runes := []rune(str)
	i := 0
	n := len(runes)
	currentText := ""

	for i < n {
		if runes[i] == '{' {
			if currentText != "" {
				formatParts = append(formatParts, currentText)
				currentText = ""
			}
			i++
			exprText := ""
			for i < n && runes[i] != '}' {
				exprText += string(runes[i])
				i++
			}
			if i >= n {
				return "", fmt.Errorf("unterminated brace in f-string")
			}
			i++ // skip '}'
			formatParts = append(formatParts, "%v")

			// Parse and codegen the interpolated expression
			exprCode, err := c.compileInlineExpr(exprText)
			if err != nil {
				// Fallback to raw text if parsing fails
				args = append(args, exprText)
			} else {
				args = append(args, exprCode)
			}
		} else {
			currentText += string(runes[i])
			i++
		}
	}
	if currentText != "" {
		formatParts = append(formatParts, currentText)
	}

	formatStr := strings.Join(formatParts, "")
	if len(args) == 0 {
		return fmt.Sprintf("%q", formatStr), nil
	}
	c.imports[`"fmt"`] = true
	return fmt.Sprintf("fmt.Sprintf(%q, %s)", formatStr, strings.Join(args, ", ")), nil
}

// compileInlineExpr parses and generates Go code for a single expression string.
// Used by f-string interpolation to properly handle self.field -> self.Field etc.
func (c *Codegen) compileInlineExpr(exprText string) (string, error) {
	lexer := NewLexer(exprText)
	parser := NewParser(lexer)
	// Parse as a single expression
	expr := parser.parseExpression(LOWEST)
	if expr == nil || len(parser.Errors()) > 0 {
		return "", fmt.Errorf("failed to parse inline expression")
	}
	return c.genExpression(expr)
}

func toGoType(t string) string {
	switch t {
	case "int":
		return "int"
	case "string":
		return "string"
	case "float":
		return "float64"
	case "bool":
		return "bool"
	default:
		return "interface{}"
	}
}

func zeroValue(goType string) string {
	switch goType {
	case "int":
		return "0"
	case "float64":
		return "0.0"
	case "bool":
		return "false"
	case "string":
		return `""`
	default:
		return "nil"
	}
}

func (c *Codegen) getExpressionType(expr Expression) string {
	switch e := expr.(type) {
	case *Identifier:
		if t, ok := c.varTypes[e.Value]; ok {
			return t
		}
		return "interface{}"
	case *IntegerLiteral:
		return "int"
	case *FloatLiteral:
		return "float64"
	case *ArrayLiteral:
		return "[]interface{}"
	case *StringLiteral:
		return "string"
	case *DurationLiteral:
		return "string"
	case *BooleanLiteral:
		return "bool"
	case *NilLiteral:
		return "interface{}"
	case *StructLiteral:
		return e.TypeName
	case *SelfExpr:
		if t, ok := c.varTypes["self"]; ok {
			return t
		}
		return "interface{}"
	case *InfixExpr:
		switch e.Operator {
		case "==", "!=", "<", ">", "<=", ">=":
			return "bool"
		default:
			lt := c.getExpressionType(e.Left)
			rt := c.getExpressionType(e.Right)
			if lt == rt && (lt == "int" || lt == "float64" || lt == "string" || lt == "bool") {
				return lt
			}
			return "interface{}"
		}
	default:
		return "interface{}"
	}
}

func hasConcurrency(node Node) bool {
	if node == nil {
		return false
	}
	switch s := node.(type) {
	case *SpawnStmt, *PublishStmt:
		return true
	case *BlockStmt:
		for _, sub := range s.Statements {
			if hasConcurrency(sub) {
				return true
			}
		}
	case *TryCatchStmt:
		return hasConcurrency(s.TryBody) || hasConcurrency(s.CatchBody)
	case *MatchStmt:
		for _, cs := range s.Cases {
			if hasConcurrency(cs.Body) {
				return true
			}
		}
	case *IfStmt:
		if hasConcurrency(s.Body) {
			return true
		}
		if s.ElseBody != nil {
			return hasConcurrency(s.ElseBody)
		}
	case *ForStmt:
		return hasConcurrency(s.Body)
	case *LetStmt:
		return hasConcurrency(s.Value)
	case *ExprStmt:
		return hasConcurrency(s.Value)
	case *ReturnStmt:
		return hasConcurrency(s.Value)
	}
	return false
}

// stmtToken extracts the Token from a statement for source line tracking.
func stmtToken(stmt Statement) Token {
	switch s := stmt.(type) {
	case *LetStmt:
		return s.Token
	case *FnDecl:
		return s.Token
	case *RouteStmt:
		return s.Token
	case *EveryStmt:
		return s.Token
	case *CronStmt:
		return s.Token
	case *SubscribeStmt:
		return s.Token
	case *PublishStmt:
		return s.Token
	case *SpawnStmt:
		return s.Token
	case *ExternFnStmt:
		return s.Token
	case *BrokerStmt:
		return s.Token
	case *ServerStmt:
		return s.Token
	case *DatabaseStmt:
		return s.Token
	case *CacheStmt:
		return s.Token
	case *TryCatchStmt:
		return s.Token
	case *MatchStmt:
		return s.Token
	case *TestStmt:
		return s.Token
	case *EnumStmt:
		return s.Token
	case *ToolStmt:
		return s.Token
	case *MigrationStmt:
		return s.Token
	case *IfStmt:
		return s.Token
	case *ForStmt:
		return s.Token
	case *StructDecl:
		return s.Token
	case *MethodDecl:
		return s.Token
	case *InterfaceDecl:
		return s.Token
	case *ExportStmt:
		return stmtToken(s.Inner)
	case *ExprStmt:
		return s.Token
	case *ReturnStmt:
		return s.Token
	default:
		return Token{}
	}
}

