package dap_test

import (
	"os"
	"path/filepath"
	"testing"

	"serv/dap"
)

// sampleGenGo is a representative snippet of what the Serv codegen produces.
// Each "// .srv line N" comment precedes the Go statement it maps to.
const sampleGenGo = `// Code generated by Serv compiler. DO NOT EDIT.
package main

import (
	"serv/runtime"
	"fmt"
)

var _ = runtime.Noop
var _ = fmt.Sprintf

// .srv line 3
func greet(name string) string {
// .srv line 4
	return "Hello " + name
}

// .srv line 7
func add(a int, b int) int {
// .srv line 8
	result := a + b
// .srv line 9
	return result
}

// .srv line 12
func main_serv() {
// .srv line 13
	fmt.Println(greet("world"))
// .srv line 14
	fmt.Println(add(1, 2))
}
`

func writeTemp(t *testing.T, content string) string {
	t.Helper()
	dir := t.TempDir()
	path := filepath.Join(dir, "main.go")
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		t.Fatalf("write temp: %v", err)
	}
	return path
}

// TestParseSourceMap verifies that ParseSourceMap correctly extracts all
// "// .srv line N" comment markers and builds the mapping.
func TestParseSourceMap(t *testing.T) {
	goFile := writeTemp(t, sampleGenGo)
	sm, err := dap.ParseSourceMap(goFile, "test.srv")
	if err != nil {
		t.Fatalf("ParseSourceMap: %v", err)
	}

	if sm.Len() == 0 {
		t.Fatal("expected non-empty source map, got 0 entries")
	}
}

// TestGoToSrv verifies that known Go lines map to the correct .srv lines.
func TestGoToSrv(t *testing.T) {
	goFile := writeTemp(t, sampleGenGo)
	sm, err := dap.ParseSourceMap(goFile, "test.srv")
	if err != nil {
		t.Fatalf("ParseSourceMap: %v", err)
	}

	// Line 11 is "// .srv line 3", line 12 is the func declaration.
	// We expect goLine 12 → srvLine 3.
	cases := []struct {
		goLine  int
		wantSrv int
	}{
		{12, 3},  // func greet → srv line 3
		{14, 4},  // return "Hello" → srv line 4
		{18, 7},  // func add → srv line 7
		{20, 8},  // result := → srv line 8
		{22, 9},  // return result → srv line 9
		{26, 12}, // func main_serv → srv line 12
		{28, 13}, // fmt.Println(greet) → srv line 13
		{30, 14}, // fmt.Println(add) → srv line 14
	}

	for _, tc := range cases {
		srvLine, ok := sm.GoToSrv(tc.goLine)
		if !ok {
			t.Errorf("GoToSrv(%d): no mapping found, want srvLine %d", tc.goLine, tc.wantSrv)
			continue
		}
		if srvLine != tc.wantSrv {
			t.Errorf("GoToSrv(%d) = %d, want %d", tc.goLine, srvLine, tc.wantSrv)
		}
	}
}

// TestSrvToGo verifies that .srv lines map to valid Go lines.
func TestSrvToGo(t *testing.T) {
	goFile := writeTemp(t, sampleGenGo)
	sm, err := dap.ParseSourceMap(goFile, "test.srv")
	if err != nil {
		t.Fatalf("ParseSourceMap: %v", err)
	}

	srvLines := []int{3, 4, 7, 8, 9, 12, 13, 14}
	for _, srvLine := range srvLines {
		goLine, ok := sm.SrvToGo(srvLine)
		if !ok {
			t.Errorf("SrvToGo(%d): no mapping found", srvLine)
			continue
		}
		if goLine <= 0 {
			t.Errorf("SrvToGo(%d) = %d, want positive line number", srvLine, goLine)
		}
		// Round-trip: GoToSrv(SrvToGo(N)) should return N (or nearest).
		roundTrip, rtOk := sm.GoToSrv(goLine)
		if !rtOk {
			t.Errorf("round-trip: GoToSrv(SrvToGo(%d)=%d): not found", srvLine, goLine)
			continue
		}
		if roundTrip != srvLine {
			t.Errorf("round-trip srv %d → go %d → srv %d (mismatch)", srvLine, goLine, roundTrip)
		}
	}
}

// TestNearestGoLine verifies that a .srv line with no exact match falls back
// to the nearest mapped line rather than returning not-found.
func TestNearestGoLine(t *testing.T) {
	goFile := writeTemp(t, sampleGenGo)
	sm, err := dap.ParseSourceMap(goFile, "test.srv")
	if err != nil {
		t.Fatalf("ParseSourceMap: %v", err)
	}

	// srv line 5 and 6 have no direct mapping in the sample (they are blank
	// lines / closing braces between functions). The nearest should be 4 or 7.
	goLine, ok := sm.SrvToGo(5)
	if !ok {
		t.Fatal("SrvToGo(5) returned not-found; expected nearest fallback")
	}
	if goLine <= 0 {
		t.Errorf("SrvToGo(5) = %d, want positive line number", goLine)
	}
	t.Logf("SrvToGo(5) → goLine %d (nearest fallback)", goLine)
}

// TestEmptyFile verifies that an empty generated file produces an empty
// source map without error.
func TestEmptyFile(t *testing.T) {
	goFile := writeTemp(t, "package main\n\nfunc main() {}\n")
	sm, err := dap.ParseSourceMap(goFile, "empty.srv")
	if err != nil {
		t.Fatalf("ParseSourceMap on empty file: %v", err)
	}
	if sm.Len() != 0 {
		t.Errorf("expected 0 entries for file with no srv comments, got %d", sm.Len())
	}
	// SrvToGo on empty map should still return false without panicking.
	_, ok := sm.SrvToGo(1)
	if ok {
		t.Error("SrvToGo(1) on empty map should return ok=false")
	}
}

// TestMissingFile verifies that ParseSourceMap returns a clear error for a
// non-existent file path.
func TestMissingFile(t *testing.T) {
	_, err := dap.ParseSourceMap("/nonexistent/path/main.go", "test.srv")
	if err == nil {
		t.Fatal("expected error for missing file, got nil")
	}
}
