// Auto-generated declaration for github.com/google/uuid
// Generated by: serv add github.com/google/uuid

declare module "github.com/google/uuid" {
    fn ClockSequence() -> int
    fn DisableRandPool()
    fn EnableRandPool()
    fn IsInvalidLengthError(err: string) -> bool
    fn NewString() -> string
    fn NodeID() -> string
    fn NodeInterface() -> string
    fn SetClockSequence(seq: int)
    fn SetNodeID(id: string) -> bool
    fn SetNodeInterface(name: string) -> bool
    fn SetRand(r: string)
    fn Validate(s: string) -> string
    fn! GetTime() -> string
    fn! FromBytes(b: string) -> string
    fn Must(uuid: string, err: string) -> string
    fn MustParse(s: string) -> string
    fn New() -> string
    fn! NewDCEGroup() -> string
    fn! NewDCEPerson() -> string
    fn! NewDCESecurity(domain: string, id: string) -> string
    fn NewHash(h: string, space: string, data: string, version: int) -> string
    fn NewMD5(space: string, data: string) -> string
    fn! NewRandom() -> string
    fn! NewRandomFromReader(r: string) -> string
    fn NewSHA1(space: string, data: string) -> string
    fn! NewUUID() -> string
    fn! NewV6() -> string
    fn! NewV7() -> string
    fn! NewV7FromReader(r: string) -> string
    fn! Parse(s: string) -> string
    fn! ParseBytes(b: string) -> string
}
