package compiler

import (
	"encoding/json"
	"strings"
)

type OpenAPIInfo struct {
	Title   string `json:"title"`
	Version string `json:"version"`
}

type OpenAPISchema struct {
	Type                 string                    `json:"type,omitempty"`
	Properties           map[string]*OpenAPISchema `json:"properties,omitempty"`
	Items                *OpenAPISchema            `json:"items,omitempty"`
	Ref                  string                    `json:"$ref,omitempty"`
	Required             []string                  `json:"required,omitempty"`
}

type OpenAPIParameter struct {
	Name     string         `json:"name"`
	In       string         `json:"in"`
	Required bool           `json:"required"`
	Schema   *OpenAPISchema `json:"schema"`
}

type OpenAPIMediaType struct {
	Schema *OpenAPISchema `json:"schema"`
}

type OpenAPIRequestBody struct {
	Content map[string]*OpenAPIMediaType `json:"content"`
}

type OpenAPIResponse struct {
	Description string                       `json:"description"`
	Content     map[string]*OpenAPIMediaType `json:"content,omitempty"`
}

type OpenAPIOperation struct {
	Summary     string                      `json:"summary,omitempty"`
	Description string                      `json:"description,omitempty"`
	Parameters  []*OpenAPIParameter         `json:"parameters,omitempty"`
	RequestBody *OpenAPIRequestBody         `json:"requestBody,omitempty"`
	Responses   map[string]*OpenAPIResponse `json:"responses"`
}

type OpenAPIComponents struct {
	Schemas map[string]*OpenAPISchema `json:"schemas,omitempty"`
}

type OpenAPI3 struct {
	OpenAPI    string                       `json:"openapi"`
	Info       OpenAPIInfo                  `json:"info"`
	Paths      map[string]map[string]*OpenAPIOperation `json:"paths"`
	Components OpenAPIComponents            `json:"components,omitempty"`
}

func GenerateOpenAPI(prog *Program) (string, error) {
	doc := OpenAPI3{
		OpenAPI: "3.1.0",
		Info: OpenAPIInfo{
			Title:   "Servverse Autogenerated API",
			Version: "1.0.0",
		},
		Paths: make(map[string]map[string]*OpenAPIOperation),
		Components: OpenAPIComponents{
			Schemas: make(map[string]*OpenAPISchema),
		},
	}

	// 1. First, extract all struct declarations
	var structs []*StructDecl
	var routes []*RouteStmt

	var collect func(statements []Statement)
	collect = func(statements []Statement) {
		for _, stmt := range statements {
			switch s := stmt.(type) {
			case *StructDecl:
				structs = append(structs, s)
			case *RouteStmt:
				routes = append(routes, s)
			case *ExportStmt:
				switch inner := s.Inner.(type) {
				case *StructDecl:
					structs = append(structs, inner)
				case *RouteStmt:
					routes = append(routes, inner)
				}
			case *AppStmt:
				if s.Body != nil {
					collect(s.Body.Statements)
				}
			}
		}
	}
	collect(prog.Statements)

	// 2. Build Components/Schemas
	for _, s := range structs {
		schema := &OpenAPISchema{
			Type:       "object",
			Properties: make(map[string]*OpenAPISchema),
		}

		for _, field := range s.Fields {
			schema.Properties[field.Name] = parseTypeToSchema(field.Type)
		}
		doc.Components.Schemas[s.Name] = schema
	}

	// 3. Build Paths
	for _, route := range routes {
		// Parse URL parameters from path: /api/tasks/:id -> /api/tasks/{id}
		openApiPath, pathParams := convertPath(route.Path)

		op := &OpenAPIOperation{
			Summary:    route.Method + " " + route.Path,
			Responses:  make(map[string]*OpenAPIResponse),
			Parameters: []*OpenAPIParameter{},
		}

		// Add Path Parameters
		for _, pName := range pathParams {
			op.Parameters = append(op.Parameters, &OpenAPIParameter{
				Name:     pName,
				In:       "path",
				Required: true,
				Schema:   &OpenAPISchema{Type: "string"},
			})
		}

		// Add Request Body if POST/PUT
		methodLower := strings.ToLower(route.Method)
		if methodLower == "post" || methodLower == "put" || methodLower == "patch" {
			reqSchema := &OpenAPISchema{
				Type:       "object",
				Properties: make(map[string]*OpenAPISchema),
			}

			rules, keys := parseValidationMap(route.Body)
			if len(rules) > 0 {
				for _, k := range keys {
					ruleVal := rules[k]
					fieldSchema := &OpenAPISchema{}
					if strings.Contains(ruleVal, "string") || strings.Contains(ruleVal, "email") {
						fieldSchema.Type = "string"
					} else if strings.Contains(ruleVal, "int") {
						fieldSchema.Type = "integer"
					} else if strings.Contains(ruleVal, "float") {
						fieldSchema.Type = "number"
					} else if strings.Contains(ruleVal, "bool") {
						fieldSchema.Type = "boolean"
					} else {
						fieldSchema.Type = "string"
					}
					reqSchema.Properties[k] = fieldSchema
					if strings.Contains(ruleVal, "required") {
						reqSchema.Required = append(reqSchema.Required, k)
					}
				}
			}

			op.RequestBody = &OpenAPIRequestBody{
				Content: map[string]*OpenAPIMediaType{
					"application/json": {
						Schema: reqSchema,
					},
				},
			}
		}

		// Configure Responses
		resp := &OpenAPIResponse{
			Description: "Successful operation",
		}
		if route.Stream {
			resp.Content = map[string]*OpenAPIMediaType{
				"text/event-stream": {
					Schema: &OpenAPISchema{Type: "string"},
				},
			}
		} else {
			resp.Content = map[string]*OpenAPIMediaType{
				"application/json": {
					Schema: &OpenAPISchema{Type: "object"},
				},
			}
		}
		op.Responses["200"] = resp

		if _, exists := doc.Paths[openApiPath]; !exists {
			doc.Paths[openApiPath] = make(map[string]*OpenAPIOperation)
		}
		doc.Paths[openApiPath][methodLower] = op
	}

	bytes, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		return "", err
	}
	return string(bytes), nil
}

func convertPath(path string) (string, []string) {
	parts := strings.Split(path, "/")
	var newParts []string
	var params []string
	for _, part := range parts {
		if strings.HasPrefix(part, ":") {
			pName := strings.TrimPrefix(part, ":")
			newParts = append(newParts, "{"+pName+"}")
			params = append(params, pName)
		} else {
			newParts = append(newParts, part)
		}
	}
	return strings.Join(newParts, "/"), params
}

func parseTypeToSchema(typ string) *OpenAPISchema {
	isSlice := strings.HasPrefix(typ, "[]")
	if isSlice {
		elemType := strings.TrimPrefix(typ, "[]")
		return &OpenAPISchema{
			Type:  "array",
			Items: parseTypeToSchema(elemType),
		}
	}

	cleanType := strings.TrimSuffix(typ, "?")

	switch cleanType {
	case "string":
		return &OpenAPISchema{Type: "string"}
	case "int", "integer":
		return &OpenAPISchema{Type: "integer"}
	case "float", "float64", "double":
		return &OpenAPISchema{Type: "number"}
	case "bool", "boolean":
		return &OpenAPISchema{Type: "boolean"}
	case "any", "object":
		return &OpenAPISchema{Type: "object"}
	default:
		// Custom struct reference
		return &OpenAPISchema{Ref: "#/components/schemas/" + cleanType}
	}
}

func parseValidationMap(body *BlockStmt) (map[string]string, []string) {
	if body == nil {
		return nil, nil
	}

	var findValidate func(stmts []Statement) *CallExpr
	findValidate = func(stmts []Statement) *CallExpr {
		for _, stmt := range stmts {
			switch s := stmt.(type) {
			case *LetStmt:
				if call, ok := s.Value.(*CallExpr); ok {
					if ident, ok := call.Function.(*Identifier); ok && ident.Value == "validate" {
						return call
					}
				}
			case *ExprStmt:
				if call, ok := s.Value.(*CallExpr); ok {
					if ident, ok := call.Function.(*Identifier); ok && ident.Value == "validate" {
						return call
					}
				}
			case *IfStmt:
				if call := findValidate(s.Body.Statements); call != nil {
					return call
				}
				if s.ElseBody != nil {
					if call := findValidate(s.ElseBody.Statements); call != nil {
						return call
					}
				}
			case *BlockStmt:
				if call := findValidate(s.Statements); call != nil {
					return call
				}
			case *ForStmt:
				if call := findValidate(s.Body.Statements); call != nil {
					return call
				}
			case *TryCatchStmt:
				if call := findValidate(s.TryBody.Statements); call != nil {
					return call
				}
				if s.CatchBody != nil {
					if call := findValidate(s.CatchBody.Statements); call != nil {
						return call
					}
				}
			}
		}
		return nil
	}

	call := findValidate(body.Statements)
	if call == nil || len(call.Arguments) < 2 {
		return nil, nil
	}

	mapLit, ok := call.Arguments[1].(*MapLiteral)
	if !ok {
		return nil, nil
	}

	rules := make(map[string]string)
	var keys []string

	for _, key := range mapLit.KeyOrder {
		expr := mapLit.Pairs[key]
		if strLit, ok := expr.(*StringLiteral); ok {
			rules[key] = strLit.Value
			keys = append(keys, key)
		}
	}

	return rules, keys
}
